<?php
namespace App\Http\Requests;
use App\Support\Decimal;
use Illuminate\Validation\Rule;
final class OperationRules {
    public static function money():array{return ['required','string',Decimal::MONEY_RULE];}
    public static function date():array{return ['required','date_format:Y-m-d','before_or_equal:today'];}
    public static function schedule():array{return ['installment_count'=>['nullable','integer','between:1,360'],'first_due_date'=>['nullable','date_format:Y-m-d'],'frequency'=>['nullable',Rule::in(['weekly','fortnightly','monthly'])],'schedule'=>['sometimes','array','max:360'],'schedule.*'=>['array:due_date,amount'],'schedule.*.due_date'=>['required','date_format:Y-m-d'],'schedule.*.amount'=>self::money()];}
    public static function payment():array{return ['customer_id'=>['required','integer','exists:customers,id'],'document_date'=>self::date(),'currency'=>['required','string','size:3'],'amount'=>self::money(),'method'=>['required',Rule::in(['cash','bank'])],'cashbox_id'=>['nullable','required_if:method,cash','integer','exists:cashboxes,id'],'bank_account_id'=>['nullable','required_if:method,bank','integer','exists:bank_accounts,id'],'payment_reference'=>['nullable','string','max:160'],'notes'=>['nullable','string','max:3000'],'allocations'=>['sometimes','array','max:100'],'allocations.*'=>['array:sales_invoice_id,amount'],'allocations.*.sales_invoice_id'=>['required','integer','distinct','exists:sales_invoices,id'],'allocations.*.amount'=>self::money()];}
    public static function check():array{return ['customer_id'=>['required','integer','exists:customers,id'],'check_no'=>['required','string','max:80'],'bank_name'=>['required','string','max:120'],'bank_branch'=>['nullable','string','max:120'],'payer_name'=>['required','string','max:200'],'account_reference'=>['required','string','max:120'],'currency'=>['required','string','size:3'],'amount'=>self::money(),'issue_date'=>['required','date_format:Y-m-d','before_or_equal:due_date'],'received_date'=>self::date(),'due_date'=>['required','date_format:Y-m-d'],'notes'=>['nullable','string','max:3000'],'allocations'=>['sometimes','array','max:100'],'allocations.*'=>['array:sales_invoice_id,amount,installment_schedule_id'],'allocations.*.sales_invoice_id'=>['required','integer','distinct','exists:sales_invoices,id'],'allocations.*.amount'=>self::money(),'allocations.*.installment_schedule_id'=>['nullable','integer','exists:installment_schedule,id']];}
}
