-- «دفتر»: العملاء والمنتجات (بدون صور ولا مخزون ولا حركات).
-- آمن للتشغيل أكثر من مرة: كل سجل يُضاف فقط إن لم يكن موجوداً، ولا يُعدَّل أو يُحذف أي شيء.
-- يتطلب وجود حساب المالك أولاً (erp:create-owner). التشغيل:  mysql -u erp -p erp < daftar-customers-products.sql
-- 20 منتج، 20 باركود، 13 عميل.
SET NAMES utf8mb4;
START TRANSACTION;

-- المالك هو من يُسجَّل كمنشئ للسجلات. إن لم يوجد، يتوقف الملف عند أول إدخال ولا يُحفظ شيء.
SET @owner := (SELECT ur.user_id FROM user_roles ur JOIN roles r ON r.id = ur.role_id WHERE r.name = 'owner' ORDER BY ur.user_id LIMIT 1);

-- وحدات القياس
INSERT INTO units (code, name_ar, decimal_places) SELECT 'piece', 'قطعة', 0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM units WHERE code = 'piece');

-- رموز الضريبة (راجع النسبة مع المحاسب)
INSERT INTO tax_codes (code, name_ar, category, rate, effective_from, effective_to, input_account_id, output_account_id) SELECT 'VAT16', 'ضريبة القيمة المضافة 16% (بيانات تجريبية)', 'standard', 16.0, '2026-01-01', NULL, (SELECT id FROM accounts WHERE code = '1400'), (SELECT id FROM accounts WHERE code = '2200') FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tax_codes WHERE code = 'VAT16');

-- الماركات
INSERT INTO brands (name_ar, name_en, active, created_at, updated_at) SELECT 'LG', 'LG', 1, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM brands WHERE name_ar = 'LG');
INSERT INTO brands (name_ar, name_en, active, created_at, updated_at) SELECT 'Samsung', 'Samsung', 1, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM brands WHERE name_ar = 'Samsung');
INSERT INTO brands (name_ar, name_en, active, created_at, updated_at) SELECT 'Bosch', 'Bosch', 1, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM brands WHERE name_ar = 'Bosch');
INSERT INTO brands (name_ar, name_en, active, created_at, updated_at) SELECT 'Beko', 'Beko', 1, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM brands WHERE name_ar = 'Beko');
INSERT INTO brands (name_ar, name_en, active, created_at, updated_at) SELECT 'Ariston', 'Ariston', 1, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM brands WHERE name_ar = 'Ariston');
INSERT INTO brands (name_ar, name_en, active, created_at, updated_at) SELECT 'Toshiba', 'Toshiba', 1, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM brands WHERE name_ar = 'Toshiba');
INSERT INTO brands (name_ar, name_en, active, created_at, updated_at) SELECT 'Hisense', 'Hisense', 1, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM brands WHERE name_ar = 'Hisense');
INSERT INTO brands (name_ar, name_en, active, created_at, updated_at) SELECT 'Midea', 'Midea', 1, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM brands WHERE name_ar = 'Midea');
INSERT INTO brands (name_ar, name_en, active, created_at, updated_at) SELECT 'Panasonic', 'Panasonic', 1, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM brands WHERE name_ar = 'Panasonic');
INSERT INTO brands (name_ar, name_en, active, created_at, updated_at) SELECT 'National', 'National', 1, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM brands WHERE name_ar = 'National');

-- التصنيفات
INSERT INTO categories (name_ar, name_en, slug, active, sort_order, created_at, updated_at) SELECT 'ثلاجات وفريزرات', 'Refrigerators', 'ref', 1, 0, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'ref');
INSERT INTO categories (name_ar, name_en, slug, active, sort_order, created_at, updated_at) SELECT 'غسالات ملابس', 'Washing machines', 'wm', 1, 0, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'wm');
INSERT INTO categories (name_ar, name_en, slug, active, sort_order, created_at, updated_at) SELECT 'غسالات صحون', 'Dishwashers', 'dw', 1, 0, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'dw');
INSERT INTO categories (name_ar, name_en, slug, active, sort_order, created_at, updated_at) SELECT 'أفران وطباخات', 'Ovens and cookers', 'ovn', 1, 0, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'ovn');
INSERT INTO categories (name_ar, name_en, slug, active, sort_order, created_at, updated_at) SELECT 'مكيفات', 'Air conditioners', 'ac', 1, 0, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'ac');
INSERT INTO categories (name_ar, name_en, slug, active, sort_order, created_at, updated_at) SELECT 'سخانات مياه', 'Water heaters', 'wh', 1, 0, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'wh');
INSERT INTO categories (name_ar, name_en, slug, active, sort_order, created_at, updated_at) SELECT 'مكانس كهربائية', 'Vacuum cleaners', 'vac', 1, 0, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'vac');
INSERT INTO categories (name_ar, name_en, slug, active, sort_order, created_at, updated_at) SELECT 'أجهزة مطبخ صغيرة', 'Small appliances', 'sda', 1, 0, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'sda');

-- سياسات الضمان
INSERT INTO warranty_policies (name_ar, duration_value, duration_unit, provider_type, terms, active, created_at, updated_at) SELECT 'ضمان الوكيل سنة واحدة', 1, 'year', 'agent', 'الضمان لدى الوكيل المعتمد ولا يشمل سوء الاستخدام.', 1, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM warranty_policies WHERE name_ar = 'ضمان الوكيل سنة واحدة');
INSERT INTO warranty_policies (name_ar, duration_value, duration_unit, provider_type, terms, active, created_at, updated_at) SELECT 'ضمان الوكيل سنتان', 2, 'year', 'agent', 'الضمان لدى الوكيل المعتمد ولا يشمل سوء الاستخدام.', 1, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM warranty_policies WHERE name_ar = 'ضمان الوكيل سنتان');
INSERT INTO warranty_policies (name_ar, duration_value, duration_unit, provider_type, terms, active, created_at, updated_at) SELECT 'ضمان الكمبروسر 5 سنوات', 5, 'year', 'agent', 'الضمان لدى الوكيل المعتمد ولا يشمل سوء الاستخدام.', 1, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM warranty_policies WHERE name_ar = 'ضمان الكمبروسر 5 سنوات');

-- المنتجات (المخزون يبدأ صفراً؛ أدخله بمستند «رصيد افتتاحي»)
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'LG-REF-GN730', 'ثلاجة LG نوفروست 730 لتر', 'LG No Frost Refrigerator 730L', 'GN-C732HQCL', (SELECT id FROM brands WHERE name_ar = 'LG' LIMIT 1), (SELECT id FROM categories WHERE slug = 'ref' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الكمبروسر 5 سنوات' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 3200.0, 4300.0, 4900.0, 3900.0, 2.0, '[{"name": "السعة", "value": "730 لتر"}, {"name": "النوع", "value": "بابين نوفروست"}, {"name": "اللون", "value": "ستيل"}]', 'A+', 'كوريا', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'LG-REF-GN730');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'LG-REF-GN340', 'ثلاجة LG 340 لتر', 'LG Refrigerator 340L', 'GN-B342SQBB', (SELECT id FROM brands WHERE name_ar = 'LG' LIMIT 1), (SELECT id FROM categories WHERE slug = 'ref' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الوكيل سنتان' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 1900.0, 2600.0, 2950.0, 2350.0, 2.0, '[{"name": "السعة", "value": "340 لتر"}, {"name": "اللون", "value": "أسود"}]', 'A', 'كوريا', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'LG-REF-GN340');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'LG-WM-F4V5', 'غسالة LG أوتوماتيك 9 كغم', 'LG Front Load Washer 9kg', 'F4V5VYP2T', (SELECT id FROM brands WHERE name_ar = 'LG' LIMIT 1), (SELECT id FROM categories WHERE slug = 'wm' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الوكيل سنتان' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 2100.0, 2850.0, 3250.0, 2600.0, 2.0, '[{"name": "السعة", "value": "9 كغم"}, {"name": "الدورة", "value": "1400 لفة"}]', 'A+++', 'كوريا', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'LG-WM-F4V5');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'LG-AC-S18', 'مكيف LG انفرتر 1.5 طن', 'LG Inverter Split AC 18000BTU', 'S4-W18KL3AA', (SELECT id FROM brands WHERE name_ar = 'LG' LIMIT 1), (SELECT id FROM categories WHERE slug = 'ac' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الكمبروسر 5 سنوات' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 2400.0, 3200.0, 3650.0, 2900.0, 2.0, '[{"name": "القدرة", "value": "18000 BTU"}, {"name": "النوع", "value": "انفرتر"}]', 'A++', 'كوريا', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'LG-AC-S18');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'SAM-REF-RT50', 'ثلاجة Samsung تويين كولينغ 500 لتر', 'Samsung Twin Cooling 500L', 'RT50K6340S8', (SELECT id FROM brands WHERE name_ar = 'Samsung' LIMIT 1), (SELECT id FROM categories WHERE slug = 'ref' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الكمبروسر 5 سنوات' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 2800.0, 3800.0, 4300.0, 3400.0, 2.0, '[{"name": "السعة", "value": "500 لتر"}, {"name": "التقنية", "value": "تبريد مزدوج"}]', 'A+', 'كوريا', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'SAM-REF-RT50');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'SAM-WM-WW90', 'غسالة Samsung إيكو بابل 9 كغم', 'Samsung EcoBubble Washer 9kg', 'WW90T504DAE', (SELECT id FROM brands WHERE name_ar = 'Samsung' LIMIT 1), (SELECT id FROM categories WHERE slug = 'wm' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الوكيل سنتان' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 2200.0, 2950.0, 3400.0, 2700.0, 2.0, '[{"name": "السعة", "value": "9 كغم"}, {"name": "التقنية", "value": "إيكو بابل"}]', 'A+++', 'بولندا', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'SAM-WM-WW90');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'SAM-MW-MS23', 'مايكروويف Samsung 23 لتر', 'Samsung Microwave 23L', 'MS23K3513AK', (SELECT id FROM brands WHERE name_ar = 'Samsung' LIMIT 1), (SELECT id FROM categories WHERE slug = 'sda' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الوكيل سنة واحدة' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 380.0, 540.0, 620.0, 480.0, 2.0, '[{"name": "السعة", "value": "23 لتر"}, {"name": "القدرة", "value": "800 واط"}]', 'A', 'ماليزيا', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'SAM-MW-MS23');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'BSH-DW-SMS4', 'غسالة صحون Bosch 12 طقم', 'Bosch Dishwasher 12 Place', 'SMS4HVI33E', (SELECT id FROM brands WHERE name_ar = 'Bosch' LIMIT 1), (SELECT id FROM categories WHERE slug = 'dw' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الوكيل سنتان' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 2500.0, 3400.0, 3900.0, 3100.0, 2.0, '[{"name": "السعة", "value": "12 طقم"}, {"name": "البرامج", "value": "6 برامج"}]', 'A++', 'ألمانيا', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'BSH-DW-SMS4');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'BSH-OV-HBF534', 'فرن Bosch مدمج كهربائي', 'Bosch Built-in Oven', 'HBF534ES0M', (SELECT id FROM brands WHERE name_ar = 'Bosch' LIMIT 1), (SELECT id FROM categories WHERE slug = 'ovn' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الوكيل سنتان' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 2000.0, 2750.0, 3150.0, 2500.0, 2.0, '[{"name": "السعة", "value": "66 لتر"}, {"name": "النوع", "value": "مدمج"}]', 'A', 'تركيا', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'BSH-OV-HBF534');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'ARI-WH-80', 'سخان مياه Ariston 80 لتر', 'Ariston Water Heater 80L', 'PRO1-R80', (SELECT id FROM brands WHERE name_ar = 'Ariston' LIMIT 1), (SELECT id FROM categories WHERE slug = 'wh' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الوكيل سنتان' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 620.0, 880.0, 1000.0, 800.0, 2.0, '[{"name": "السعة", "value": "80 لتر"}, {"name": "القدرة", "value": "1500 واط"}]', 'B', 'إيطاليا', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'ARI-WH-80');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'ARI-WH-50', 'سخان مياه Ariston 50 لتر', 'Ariston Water Heater 50L', 'PRO1-R50', (SELECT id FROM brands WHERE name_ar = 'Ariston' LIMIT 1), (SELECT id FROM categories WHERE slug = 'wh' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الوكيل سنة واحدة' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 470.0, 680.0, 780.0, 620.0, 2.0, '[{"name": "السعة", "value": "50 لتر"}]', 'B', 'إيطاليا', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'ARI-WH-50');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'BEK-REF-RDNE', 'ثلاجة Beko 450 لتر', 'Beko Refrigerator 450L', 'RDNE450K02DX', (SELECT id FROM brands WHERE name_ar = 'Beko' LIMIT 1), (SELECT id FROM categories WHERE slug = 'ref' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الوكيل سنتان' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 2100.0, 2900.0, 3300.0, 2600.0, 2.0, '[{"name": "السعة", "value": "450 لتر"}]', 'A+', 'تركيا', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'BEK-REF-RDNE');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'BEK-WM-WTV81', 'غسالة Beko 8 كغم', 'Beko Washing Machine 8kg', 'WTV8612XS', (SELECT id FROM brands WHERE name_ar = 'Beko' LIMIT 1), (SELECT id FROM categories WHERE slug = 'wm' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الوكيل سنة واحدة' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 1500.0, 2100.0, 2400.0, 1900.0, 2.0, '[{"name": "السعة", "value": "8 كغم"}]', 'A++', 'تركيا', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'BEK-WM-WTV81');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'BEK-CK-FSE64', 'طباخ Beko غاز 4 عيون', 'Beko Gas Cooker 60cm', 'FSE64110GW', (SELECT id FROM brands WHERE name_ar = 'Beko' LIMIT 1), (SELECT id FROM categories WHERE slug = 'ovn' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الوكيل سنة واحدة' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 1250.0, 1750.0, 2000.0, 1580.0, 2.0, '[{"name": "العرض", "value": "60 سم"}, {"name": "العيون", "value": "4"}]', 'A', 'تركيا', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'BEK-CK-FSE64');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'TOS-REF-GR', 'ثلاجة Toshiba 553 لتر', 'Toshiba Refrigerator 553L', 'GR-RF610WE', (SELECT id FROM brands WHERE name_ar = 'Toshiba' LIMIT 1), (SELECT id FROM categories WHERE slug = 'ref' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الكمبروسر 5 سنوات' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 3000.0, 4100.0, 4650.0, 3700.0, 2.0, '[{"name": "السعة", "value": "553 لتر"}]', 'A+', 'تايلند', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'TOS-REF-GR');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'MID-AC-MSA12', 'مكيف Midea 1 طن', 'Midea Split AC 12000BTU', 'MSAGBU-12HRFN1', (SELECT id FROM brands WHERE name_ar = 'Midea' LIMIT 1), (SELECT id FROM categories WHERE slug = 'ac' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الكمبروسر 5 سنوات' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 1700.0, 2350.0, 2700.0, 2150.0, 2.0, '[{"name": "القدرة", "value": "12000 BTU"}]', 'A+', 'الصين', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'MID-AC-MSA12');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'HIS-AC-AS24', 'مكيف Hisense 2 طن', 'Hisense Split AC 24000BTU', 'AS-24UR4SVETG', (SELECT id FROM brands WHERE name_ar = 'Hisense' LIMIT 1), (SELECT id FROM categories WHERE slug = 'ac' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الكمبروسر 5 سنوات' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 2900.0, 3900.0, 4450.0, 3550.0, 2.0, '[{"name": "القدرة", "value": "24000 BTU"}]', 'A++', 'الصين', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'HIS-AC-AS24');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'HIS-TV-55A6', 'شاشة Hisense 55 بوصة سمارت', 'Hisense Smart TV 55"', '55A6K', (SELECT id FROM brands WHERE name_ar = 'Hisense' LIMIT 1), (SELECT id FROM categories WHERE slug = 'sda' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الوكيل سنة واحدة' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 1400.0, 1950.0, 2250.0, 1780.0, 2.0, '[{"name": "الحجم", "value": "55 بوصة"}, {"name": "الدقة", "value": "4K"}]', 'A', 'الصين', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'HIS-TV-55A6');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'PAN-VC-MC', 'مكنسة Panasonic 2000 واط', 'Panasonic Vacuum Cleaner', 'MC-CG713', (SELECT id FROM brands WHERE name_ar = 'Panasonic' LIMIT 1), (SELECT id FROM categories WHERE slug = 'vac' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الوكيل سنة واحدة' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 430.0, 620.0, 710.0, 560.0, 2.0, '[{"name": "القدرة", "value": "2000 واط"}]', 'B', 'ماليزيا', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'PAN-VC-MC');
INSERT INTO products (sku, name_ar, name_en, manufacturer_model, brand_id, category_id, unit_id, warranty_policy_id, tax_code_id, serial_tracked, standard_cost, cash_price, installment_price, minimum_price, reorder_level, specifications, energy_rating, country_of_origin, active, created_by, updated_by, created_at, updated_at) SELECT 'NAT-BL-HB', 'خلاط National 600 واط', 'National Blender 600W', 'NB-600X', (SELECT id FROM brands WHERE name_ar = 'National' LIMIT 1), (SELECT id FROM categories WHERE slug = 'sda' LIMIT 1), (SELECT id FROM units WHERE code = 'piece' LIMIT 1), (SELECT id FROM warranty_policies WHERE name_ar = 'ضمان الوكيل سنة واحدة' LIMIT 1), (SELECT id FROM tax_codes WHERE code = 'VAT16' LIMIT 1), 1, 160.0, 250.0, 290.0, 220.0, 2.0, '[{"name": "القدرة", "value": "600 واط"}]', 'B', 'الصين', 1, @owner, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'NAT-BL-HB');

-- الباركودات
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, 'E641C408E96B' FROM products p WHERE p.sku = 'LG-REF-GN730' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = 'E641C408E96B');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, '6DCE59F56310' FROM products p WHERE p.sku = 'LG-REF-GN340' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = '6DCE59F56310');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, 'E870CE08E140' FROM products p WHERE p.sku = 'LG-WM-F4V5' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = 'E870CE08E140');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, '544D96BFF1A2' FROM products p WHERE p.sku = 'LG-AC-S18' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = '544D96BFF1A2');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, 'FE13DDA97FF6' FROM products p WHERE p.sku = 'SAM-REF-RT50' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = 'FE13DDA97FF6');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, '6E975BCEEE49' FROM products p WHERE p.sku = 'SAM-WM-WW90' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = '6E975BCEEE49');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, 'DABC22CB8DD5' FROM products p WHERE p.sku = 'SAM-MW-MS23' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = 'DABC22CB8DD5');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, 'D224548AE458' FROM products p WHERE p.sku = 'BSH-DW-SMS4' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = 'D224548AE458');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, '10397ABB656B' FROM products p WHERE p.sku = 'BSH-OV-HBF534' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = '10397ABB656B');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, '2DF188F0E637' FROM products p WHERE p.sku = 'ARI-WH-80' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = '2DF188F0E637');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, 'D8199AE582EE' FROM products p WHERE p.sku = 'ARI-WH-50' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = 'D8199AE582EE');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, 'DAFAE41188A9' FROM products p WHERE p.sku = 'BEK-REF-RDNE' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = 'DAFAE41188A9');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, '1A78FD739FA3' FROM products p WHERE p.sku = 'BEK-WM-WTV81' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = '1A78FD739FA3');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, 'B7EDA73AF023' FROM products p WHERE p.sku = 'BEK-CK-FSE64' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = 'B7EDA73AF023');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, '0A1FA77F04A0' FROM products p WHERE p.sku = 'TOS-REF-GR' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = '0A1FA77F04A0');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, 'FAB510925D5D' FROM products p WHERE p.sku = 'MID-AC-MSA12' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = 'FAB510925D5D');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, '66F5559651CC' FROM products p WHERE p.sku = 'HIS-AC-AS24' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = '66F5559651CC');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, '8E522C8D9694' FROM products p WHERE p.sku = 'HIS-TV-55A6' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = '8E522C8D9694');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, '88B538F3E49B' FROM products p WHERE p.sku = 'PAN-VC-MC' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = '88B538F3E49B');
INSERT INTO product_barcodes (product_id, barcode) SELECT p.id, 'FAA41371F23C' FROM products p WHERE p.sku = 'NAT-BL-HB' AND NOT EXISTS (SELECT 1 FROM product_barcodes WHERE barcode = 'FAA41371F23C');

-- العملاء (رقم الهوية لا يُنقل: كان مشفّراً بمفتاح النظام القديم، أضفه من شاشة العميل عند الحاجة)
INSERT INTO customers (code, name, identity_number, tax_number, phone, email, address, workplace, currency, credit_limit, max_active_contracts, max_overdue_days, risk_flag, is_walk_in, active, notes, version, created_by, created_at, updated_at) SELECT 'CUS-001', 'أحمد محمود الشريف', NULL, NULL, '0599111222', NULL, 'رام الله - بيتونيا', 'معلم مدرسة', 'ILS', 5000.0, 2, 30, 'normal', 0, 1, NULL, 1, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM customers WHERE code = 'CUS-001');
INSERT INTO customers (code, name, identity_number, tax_number, phone, email, address, workplace, currency, credit_limit, max_active_contracts, max_overdue_days, risk_flag, is_walk_in, active, notes, version, created_by, created_at, updated_at) SELECT 'CUS-002', 'فاطمة حسن دراغمة', NULL, NULL, '0598222333', NULL, 'نابلس - رفيديا', 'موظفة بنك', 'ILS', 8000.0, 2, 30, 'normal', 0, 1, NULL, 1, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM customers WHERE code = 'CUS-002');
INSERT INTO customers (code, name, identity_number, tax_number, phone, email, address, workplace, currency, credit_limit, max_active_contracts, max_overdue_days, risk_flag, is_walk_in, active, notes, version, created_by, created_at, updated_at) SELECT 'CUS-003', 'محمد سليم الحاج', NULL, NULL, '0597333444', NULL, 'الخليل - وادي الهرية', 'صاحب محل', 'ILS', 12000.0, 2, 30, 'normal', 0, 1, NULL, 1, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM customers WHERE code = 'CUS-003');
INSERT INTO customers (code, name, identity_number, tax_number, phone, email, address, workplace, currency, credit_limit, max_active_contracts, max_overdue_days, risk_flag, is_walk_in, active, notes, version, created_by, created_at, updated_at) SELECT 'CUS-004', 'سارة عماد قاسم', NULL, NULL, '0596444555', NULL, 'بيت لحم - بيت جالا', 'ممرضة', 'ILS', 6000.0, 2, 30, 'normal', 0, 1, NULL, 1, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM customers WHERE code = 'CUS-004');
INSERT INTO customers (code, name, identity_number, tax_number, phone, email, address, workplace, currency, credit_limit, max_active_contracts, max_overdue_days, risk_flag, is_walk_in, active, notes, version, created_by, created_at, updated_at) SELECT 'CUS-005', 'خالد يوسف عودة', NULL, NULL, '0595555666', NULL, 'جنين - المخيم', 'سائق', 'ILS', 4000.0, 2, 30, 'normal', 0, 1, NULL, 1, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM customers WHERE code = 'CUS-005');
INSERT INTO customers (code, name, identity_number, tax_number, phone, email, address, workplace, currency, credit_limit, max_active_contracts, max_overdue_days, risk_flag, is_walk_in, active, notes, version, created_by, created_at, updated_at) SELECT 'CUS-006', 'ليلى ناصر الشوبكي', NULL, NULL, '0594666777', NULL, 'طولكرم - المركز', 'محاسبة', 'ILS', 9000.0, 2, 30, 'normal', 0, 1, NULL, 1, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM customers WHERE code = 'CUS-006');
INSERT INTO customers (code, name, identity_number, tax_number, phone, email, address, workplace, currency, credit_limit, max_active_contracts, max_overdue_days, risk_flag, is_walk_in, active, notes, version, created_by, created_at, updated_at) SELECT 'CUS-007', 'عمر فؤاد زيدان', NULL, NULL, '0593777888', NULL, 'رام الله - المصيون', 'مهندس', 'ILS', 15000.0, 2, 30, 'normal', 0, 1, NULL, 1, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM customers WHERE code = 'CUS-007');
INSERT INTO customers (code, name, identity_number, tax_number, phone, email, address, workplace, currency, credit_limit, max_active_contracts, max_overdue_days, risk_flag, is_walk_in, active, notes, version, created_by, created_at, updated_at) SELECT 'CUS-008', 'هدى سامي برهم', NULL, NULL, '0592888999', NULL, 'قلقيلية - المدينة', 'ربة منزل', 'ILS', 3500.0, 2, 30, 'normal', 0, 1, NULL, 1, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM customers WHERE code = 'CUS-008');
INSERT INTO customers (code, name, identity_number, tax_number, phone, email, address, workplace, currency, credit_limit, max_active_contracts, max_overdue_days, risk_flag, is_walk_in, active, notes, version, created_by, created_at, updated_at) SELECT 'CUS-009', 'نضال رائد أبو سنينة', NULL, NULL, '0591999000', NULL, 'الخليل - الحرس', 'تاجر', 'ILS', 20000.0, 2, 30, 'normal', 0, 1, NULL, 1, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM customers WHERE code = 'CUS-009');
INSERT INTO customers (code, name, identity_number, tax_number, phone, email, address, workplace, currency, credit_limit, max_active_contracts, max_overdue_days, risk_flag, is_walk_in, active, notes, version, created_by, created_at, updated_at) SELECT 'CUS-010', 'ريم وليد الطويل', NULL, NULL, '0590111333', NULL, 'أريحا - المركز', 'صيدلانية', 'ILS', 7000.0, 2, 30, 'normal', 0, 1, NULL, 1, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM customers WHERE code = 'CUS-010');
INSERT INTO customers (code, name, identity_number, tax_number, phone, email, address, workplace, currency, credit_limit, max_active_contracts, max_overdue_days, risk_flag, is_walk_in, active, notes, version, created_by, created_at, updated_at) SELECT 'CUS-011', 'باسل منير خضر', NULL, NULL, '0599222444', NULL, 'سلفيت - المدينة', 'موظف حكومي', 'ILS', 5500.0, 2, 30, 'normal', 0, 1, NULL, 1, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM customers WHERE code = 'CUS-011');
INSERT INTO customers (code, name, identity_number, tax_number, phone, email, address, workplace, currency, credit_limit, max_active_contracts, max_overdue_days, risk_flag, is_walk_in, active, notes, version, created_by, created_at, updated_at) SELECT 'CUS-012', 'نور الدين صالح', NULL, NULL, '0598333555', NULL, 'طوباس - المركز', 'مزارع', 'ILS', 4500.0, 2, 30, 'normal', 0, 1, NULL, 1, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM customers WHERE code = 'CUS-012');
INSERT INTO customers (code, name, identity_number, tax_number, phone, email, address, workplace, currency, credit_limit, max_active_contracts, max_overdue_days, risk_flag, is_walk_in, active, notes, version, created_by, created_at, updated_at) SELECT 'CUS-100', 'ابراهيم وصفي دويكات', NULL, NULL, '0568227764', NULL, 'بيتا بالقرب من صالة النجوم', NULL, 'ILS', 10000.0, 5, 30, 'normal', 0, 1, NULL, 1, @owner, NOW(), NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM customers WHERE code = 'CUS-100');

COMMIT;

-- للتحقق بعد التشغيل:
-- SELECT (SELECT COUNT(*) FROM products) AS products, (SELECT COUNT(*) FROM product_barcodes) AS barcodes, (SELECT COUNT(*) FROM customers) AS customers;
