-- يحذف كل العمليات (مشتريات، مبيعات، أقساط، شيكات، مصروفات، قيود، مخزون) ويُبقي المنتجات وصورها والعملاء والمستخدمين والإعدادات.
-- نسخة احتياطية قبل التشغيل: .runtime/demo-backups/before-reset-20260926-150416.sql
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `alert_reads`;
TRUNCATE TABLE `approval_steps`;
TRUNCATE TABLE `approvals`;
TRUNCATE TABLE `bank_reconciliations`;
TRUNCATE TABLE `bank_statement_lines`;
TRUNCATE TABLE `cash_transfers`;
TRUNCATE TABLE `cashier_sessions`;
TRUNCATE TABLE `check_deposit_batch_items`;
TRUNCATE TABLE `check_deposit_batches`;
TRUNCATE TABLE `check_fees`;
TRUNCATE TABLE `check_status_history`;
TRUNCATE TABLE `checks`;
TRUNCATE TABLE `customer_followups`;
TRUNCATE TABLE `customer_ledger_entries`;
TRUNCATE TABLE `customer_payments`;
TRUNCATE TABLE `customer_settlement_allocations`;
TRUNCATE TABLE `customer_settlements`;
TRUNCATE TABLE `document_sequence_counters`;
TRUNCATE TABLE `expenses`;
TRUNCATE TABLE `goods_receipt_lines`;
TRUNCATE TABLE `goods_receipts`;
TRUNCATE TABLE `idempotency_keys`;
TRUNCATE TABLE `installment_adjustments`;
TRUNCATE TABLE `installment_allocations`;
TRUNCATE TABLE `installment_contracts`;
TRUNCATE TABLE `installment_reschedules`;
TRUNCATE TABLE `installment_schedule`;
TRUNCATE TABLE `inventory_balances`;
TRUNCATE TABLE `inventory_movements`;
TRUNCATE TABLE `journal_entries`;
TRUNCATE TABLE `journal_lines`;
TRUNCATE TABLE `operational_alerts`;
TRUNCATE TABLE `payment_allocation_reversals`;
TRUNCATE TABLE `payment_allocations`;
TRUNCATE TABLE `purchase_order_lines`;
TRUNCATE TABLE `purchase_orders`;
TRUNCATE TABLE `report_exports`;
TRUNCATE TABLE `sales_invoice_lines`;
TRUNCATE TABLE `sales_invoices`;
TRUNCATE TABLE `sales_return_concessions`;
TRUNCATE TABLE `sales_return_lines`;
TRUNCATE TABLE `sales_returns`;
TRUNCATE TABLE `serial_movements`;
TRUNCATE TABLE `serial_numbers`;
TRUNCATE TABLE `stock_adjustment_lines`;
TRUNCATE TABLE `stock_adjustments`;
TRUNCATE TABLE `stock_count_lines`;
TRUNCATE TABLE `stock_counts`;
TRUNCATE TABLE `stock_transfer_lines`;
TRUNCATE TABLE `stock_transfers`;
TRUNCATE TABLE `supplier_credit_note_lines`;
TRUNCATE TABLE `supplier_credit_notes`;
TRUNCATE TABLE `supplier_invoice_lines`;
TRUNCATE TABLE `supplier_invoices`;
TRUNCATE TABLE `supplier_ledger_entries`;
TRUNCATE TABLE `supplier_payment_allocations`;
TRUNCATE TABLE `supplier_payments`;
TRUNCATE TABLE `tax_transactions`;
TRUNCATE TABLE `treasury_movements`;
TRUNCATE TABLE `warranty_claims`;
TRUNCATE TABLE `warranty_events`;
TRUNCATE TABLE `workflow_approvals`;
DELETE FROM suppliers WHERE code IN ('SUP-LG-01','SUP-SAM-02','SUP-EUR-03','SUP-BEK-04','SUP-ASIA-05','SUP-LOC-06');
UPDATE customers SET risk_flag='normal';
SET FOREIGN_KEY_CHECKS=1;
DROP DATABASE IF EXISTS erp_reset_tmp;
