<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\V1\SupplierSettlementController;
use App\Http\Controllers\Api\V1\CustomerController;
use App\Http\Controllers\Api\V1\SalesController;
use App\Http\Controllers\Api\V1\DraftDocumentController;
use App\Http\Controllers\Api\V1\CustomerPaymentController;
use App\Http\Controllers\Api\V1\InstallmentController;
use App\Http\Controllers\Api\V1\CheckController;
use App\Http\Controllers\Api\V1\TreasuryController;
use App\Http\Controllers\Api\V1\OperationsController;
use App\Http\Controllers\Api\V1\ReportController;
use App\Http\Controllers\Api\V1\DocumentController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\MfaController;

// Included inside the authenticated v1 group.
Route::get('operations/health',[\App\Http\Controllers\Api\V1\OperationsHealthController::class,'status'])->middleware('permission:settings.manage');
Route::post('operations/backups',[\App\Http\Controllers\Api\V1\OperationsHealthController::class,'backup'])->middleware('permission:settings.manage');
Route::get('customer-settlements',[\App\Http\Controllers\Api\V1\CustomerSettlementController::class,'index'])->middleware('permission:sales.view');
Route::post('customer-settlements',[\App\Http\Controllers\Api\V1\CustomerSettlementController::class,'store']);
Route::get('customer-settlements/{id}',[\App\Http\Controllers\Api\V1\CustomerSettlementController::class,'show'])->middleware('permission:sales.view');
Route::post('customer-settlements/{id}/post',[\App\Http\Controllers\Api\V1\CustomerSettlementController::class,'post']);
Route::delete('customer-settlements/{id}',[DraftDocumentController::class,'destroy'])->defaults('draftKind','customer_settlement')->middleware('permission:payments.receive');
Route::get('warranty-claims',[\App\Http\Controllers\Api\V1\WarrantyController::class,'index'])->middleware('permission:inventory.view');
Route::post('warranty-claims',[\App\Http\Controllers\Api\V1\WarrantyController::class,'store'])->middleware('permission:inventory.transfer');
Route::get('warranty-claims/{id}',[\App\Http\Controllers\Api\V1\WarrantyController::class,'show'])->middleware('permission:inventory.view');
Route::post('warranty-claims/{id}/transition',[\App\Http\Controllers\Api\V1\WarrantyController::class,'transition'])->middleware('permission:inventory.transfer');
Route::get('operations/options',[OperationsController::class,'options']);
Route::get('operations/products',[OperationsController::class,'products'])->middleware('permission:sales.view,sales.create');
Route::get('operations/policies',[OperationsController::class,'policies'])->middleware('permission:settings.manage');
Route::put('operations/policies/{key}',[OperationsController::class,'policy'])->middleware('permission:settings.manage');
Route::get('operations/approvals',[OperationsController::class,'approvals']);
Route::post('operations/approvals/{id}/decide',[OperationsController::class,'decide']);
Route::get('customers',[CustomerController::class,'index'])->middleware('permission:customers.view');
Route::post('customers',[CustomerController::class,'save'])->middleware('permission:customers.manage');
Route::get('customers/{customer}',[CustomerController::class,'show'])->middleware('permission:customers.view');
Route::put('customers/{customer}',[CustomerController::class,'save'])->middleware('permission:customers.manage');
Route::delete('customers/{customer}',[CustomerController::class,'destroy'])->middleware('permission:customers.delete');
Route::get('customers/{customer}/statement',[CustomerController::class,'statement'])->middleware('permission:customers.view');
Route::get('customers/{customer}/open-invoices',[CustomerController::class,'openInvoices'])->middleware('permission:customers.view,payments.receive');
Route::get('customers/{customer}/credit-summary',[InstallmentController::class,'credit'])->middleware('permission:customers.view');
Route::match(['GET','POST'],'customers/{customer}/followups',[CustomerController::class,'followups'])->middleware('permission:customers.view');
Route::get('sales-invoices',[SalesController::class,'index'])->middleware('permission:sales.view');
Route::get('sales-invoices/{salesInvoice}',[SalesController::class,'show'])->middleware('permission:sales.view');
Route::post('sales-invoices',[SalesController::class,'save'])->middleware('permission:sales.create');
Route::put('sales-invoices/{salesInvoice}',[SalesController::class,'save'])->middleware('permission:sales.create');
Route::post('sales-invoices/{salesInvoice}/submit',[SalesController::class,'submit'])->middleware('permission:sales.create');
Route::post('sales-invoices/{salesInvoice}/post',[SalesController::class,'post'])->middleware('permission:sales.post');
Route::delete('sales-invoices/{salesInvoice}',[DraftDocumentController::class,'destroy'])->defaults('draftKind','sales_invoice')->middleware('permission:sales.cancel');
Route::get('sales-returns',[SalesController::class,'returns'])->middleware('permission:sales.view');
Route::post('sales-returns',[SalesController::class,'returns'])->middleware('permission:sales.cancel');
Route::get('sales-returns/{id}',[SalesController::class,'returnDetail'])->middleware('permission:sales.view');
Route::post('sales-returns/{id}/post',[SalesController::class,'postReturn'])->middleware('permission:sales.cancel');
Route::delete('sales-returns/{id}',[DraftDocumentController::class,'destroy'])->defaults('draftKind','sales_return')->middleware('permission:sales.cancel');
Route::get('customer-payments',[CustomerPaymentController::class,'index'])->middleware('permission:payments.view');
Route::get('customer-payments/{customerPayment}',[CustomerPaymentController::class,'show'])->middleware('permission:payments.view');
Route::post('customer-payments',[CustomerPaymentController::class,'store'])->middleware('permission:payments.receive');
Route::post('customer-payments/{customerPayment}/post',[CustomerPaymentController::class,'post'])->middleware('permission:payments.receive');
Route::delete('customer-payments/{customerPayment}',[DraftDocumentController::class,'destroy'])->defaults('draftKind','customer_payment')->middleware('permission:payments.receive');
Route::get('installment-contracts',[InstallmentController::class,'index'])->middleware('permission:installments.view');
Route::post('installment-contracts/preview-schedule',[InstallmentController::class,'preview'])->middleware('permission:installments.create,sales.create');
Route::get('installment-contracts/{id}',[InstallmentController::class,'show'])->middleware('permission:installments.view');
Route::post('installment-contracts/{id}/checks',[InstallmentController::class,'receiveChecks'])->middleware('permission:checks.receive');
Route::post('installment-contracts/{id}/reschedules',[InstallmentController::class,'reschedule'])->middleware('permission:installments.reschedule');
Route::post('installment-reschedules/{id}/apply',[InstallmentController::class,'apply'])->middleware('permission:installments.reschedule');
Route::get('installments/due',[InstallmentController::class,'due'])->middleware('permission:installments.view');
Route::get('checks',[CheckController::class,'index'])->middleware('permission:checks.view');
Route::post('checks',[CheckController::class,'store'])->middleware('permission:checks.receive');
Route::get('checks/{id}',[CheckController::class,'show'])->middleware('permission:checks.view');
Route::put('checks/{id}/followup',[CheckController::class,'followup'])->middleware('permission:checks.deposit');
Route::match(['GET','POST'],'checks/{id}/fees',[CheckController::class,'fees'])->middleware('permission:checks.view');
foreach(['clear'=>'clear','bounce'=>'bounce','collect'=>'deposit','return'=>'return_to_customer'] as $event=>$permission)Route::post('checks/{id}/'.$event,[CheckController::class,'transition'])->defaults('checkEvent',$event)->middleware('permission:checks.'.$permission);
Route::post('checks/{id}/request-return',[CheckController::class,'requestReturn'])->middleware('permission:checks.return_to_customer');
Route::post('checks/{id}/replace',[CheckController::class,'replace'])->middleware('permission:checks.replace');
Route::post('checks/{id}/settle',[CheckController::class,'settle'])->middleware(['permission:checks.replace','permission:payments.receive']);
Route::get('checks/{id}/settlement-payments',[CheckController::class,'settlementPayments'])->middleware('permission:checks.view');
Route::post('checks/{id}/settle-existing',[CheckController::class,'settleExisting'])->middleware('permission:checks.replace');
Route::get('check-deposit-batches',[CheckController::class,'batches'])->middleware('permission:checks.view');
Route::post('check-deposit-batches',[CheckController::class,'batches'])->middleware('permission:checks.deposit');
Route::get('check-deposit-batches/{id}',[CheckController::class,'batch'])->middleware('permission:checks.view');
foreach(['expenses'=>['expenses.view','expenses.create'],'cash_transfers'=>['cashbank.view','cashbank.manage']] as $kind=>[$read,$write]){
    $path=str_replace('_','-',$kind);
    Route::get($path,[TreasuryController::class,'documents'])->defaults('treasuryKind',$kind)->middleware('permission:'.$read);
    Route::post($path,[TreasuryController::class,'documents'])->defaults('treasuryKind',$kind)->middleware('permission:'.$write);
    Route::get($path.'/{id}',[TreasuryController::class,'document'])->defaults('treasuryKind',$kind)->middleware('permission:'.$read);
    Route::post($path.'/{id}/post',[TreasuryController::class,'post'])->defaults('treasuryKind',$kind)->middleware('permission:'.$write);
    Route::delete($path.'/{id}',[DraftDocumentController::class,'destroy'])->defaults('treasuryKind',$kind)->defaults('draftKind',$kind==='expenses'?'expense':'cash_transfer')->middleware('permission:'.$write);
}
Route::get('cashier-sessions',[TreasuryController::class,'sessions'])->middleware('permission:cashbank.view,sales.post,payments.receive');
Route::post('cashier-sessions',[TreasuryController::class,'sessions'])->middleware('permission:cashbank.manage,sales.post,payments.receive');
Route::get('cashier-sessions/{id}',[TreasuryController::class,'session'])->middleware('permission:cashbank.view,sales.post,payments.receive');
Route::post('cashier-sessions/{id}/close',[TreasuryController::class,'close'])->middleware('permission:cashbank.manage,sales.post,payments.receive');
Route::get('bank-reconciliation',[TreasuryController::class,'bank'])->middleware('permission:cashbank.view');
Route::post('bank-statement-lines',[TreasuryController::class,'statementLine'])->middleware('permission:cashbank.manage');
Route::post('bank-reconciliation',[TreasuryController::class,'reconcile'])->middleware('permission:cashbank.manage');
Route::get('reports/catalog',[ReportController::class,'catalog']);
Route::get('reports/{report}',[ReportController::class,'report']);
Route::get('dashboard',[ReportController::class,'dashboard']);
Route::match(['GET','POST'],'report-exports',[ReportController::class,'exports']);
Route::get('report-exports/{id}/download',[ReportController::class,'download']);
Route::get('documents/{type}/{id}',[DocumentController::class,'index']);
Route::post('documents/{type}/{id}',[DocumentController::class,'store']);
Route::get('documents/{type}/{id}/{attachment}/download',[DocumentController::class,'download']);
Route::get('notifications',[NotificationController::class,'index']);
Route::post('notifications/{id}/read',[NotificationController::class,'read']);
Route::get('auth/mfa',[MfaController::class,'status']);
Route::post('auth/mfa/setup',[MfaController::class,'setup'])->middleware('throttle:6,1');
Route::post('auth/mfa/enable',[MfaController::class,'enable'])->middleware('throttle:6,1');
Route::post('auth/mfa/disable',[MfaController::class,'disable'])->middleware('throttle:6,1');
Route::get('purchasing/open-invoices',[SupplierSettlementController::class,'openInvoices'])->middleware('permission:purchasing.view');
Route::get('suppliers/{supplier}/statement',[SupplierSettlementController::class,'statement'])->middleware('permission:purchasing.view');
foreach (['payments'=>'pay','credit-notes'=>'invoice'] as $kind=>$permission) {
    Route::get('supplier-'.$kind,[SupplierSettlementController::class,'index'])->defaults('settlementKind',$kind)->middleware('permission:purchasing.view');
    Route::get('supplier-'.$kind.'/{id}',[SupplierSettlementController::class,'show'])->defaults('settlementKind',$kind)->middleware('permission:purchasing.view');
    Route::post('supplier-'.$kind,[SupplierSettlementController::class,'store'])->defaults('settlementKind',$kind)->middleware('permission:purchasing.'.$permission);
    Route::post('supplier-'.$kind.'/{id}/post',[SupplierSettlementController::class,'post'])->defaults('settlementKind',$kind)->middleware('permission:purchasing.'.$permission);
    Route::delete('supplier-'.$kind.'/{id}',[DraftDocumentController::class,'destroy'])->defaults('settlementKind',$kind)->defaults('draftKind',$kind==='payments'?'supplier_payment':'supplier_credit_note')->middleware('permission:purchasing.'.$permission);
}
