import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ErrorNotice, Field, Modal } from '../../components/ui/Primitives';
import { DataTable } from '../../components/data-table/DataTable';
import type { ApiEnvelope } from '../../lib/api/client';
import { useAuth } from '../../lib/auth/context';
import { SaveBar, Select, StateBadge, TextArea, money, optionRows, today, useCommand, useOptions, useRecord } from './shared';
export function CheckFollowup({id}:{id:number}){const q=useRecord<{due_date:string;followup_on?:string;classification_note?:string;status:string}>(`checks/${id}`);const fees=useRecord<{id:number;expense_id:number;amount:string;currency:string;status:string}[]>(`checks/${id}/fees`);const {can}=useAuth();const [edit,setEdit]=useState(false);const [fee,setFee]=useState(false);const nav=useNavigate();return <section className="panel ops-panel"><div className="ops-line-head"><h3>المتابعة والرسوم البنكية</h3><div className="actions">{can('checks.deposit')&&<button className="button secondary" onClick={()=>setEdit(true)}>تحديث المتابعة</button>}{can('expenses.create')&&<button className="button secondary" onClick={()=>setFee(true)}>تسجيل رسوم بنكية</button>}</div></div><p>موعد المتابعة: {q.data?.data.followup_on??'—'}</p><p>{q.data?.data.classification_note}</p><ErrorNotice error={fees.error}/><DataTable rows={fees.data?.data??[]} columns={[{key:'e',label:'المصروف',render:r=><Link to={`/treasury/expenses/${r.expense_id}`}>#{r.expense_id}</Link>},{key:'a',label:'المبلغ',render:r=><bdi>{money(r.amount)} {r.currency}</bdi>},{key:'s',label:'الحالة',render:r=><StateBadge value={r.status}/>} ]}/>{edit&&q.data&&<Modal title="متابعة الشيك" onClose={()=>setEdit(false)}><FollowupForm id={id} initial={q.data.data} onDone={()=>setEdit(false)}/></Modal>}{fee&&<Modal title="رسوم بنكية مرتبطة بالشيك" onClose={()=>setFee(false)}><FeeForm id={id} onDone={n=>nav(`/treasury/expenses/${n}`)}/></Modal>}</section>;}
function FollowupForm({id,initial,onDone}:{id:number;initial:{due_date:string;followup_on?:string;classification_note?:string;status:string};onDone:()=>void}){const c=useCommand();const [d,set]=useState({due_date:initial.due_date,followup_on:initial.followup_on??'',classification_note:initial.classification_note??'',reason:''});return <form className="ops-form" onSubmit={async e=>{e.preventDefault();if(await c.run(`checks/${id}/followup`,{...d,followup_on:d.followup_on||null},'PUT'))onDone();}}><Field label="استحقاق الشيك" type="date" value={d.due_date} disabled={initial.status!=='received'} onChange={e=>set(s=>({...s,due_date:e.target.value}))}/><Field label="المتابعة القادمة" type="date" value={d.followup_on} onChange={e=>set(s=>({...s,followup_on:e.target.value}))}/><TextArea label="ملاحظة تصنيف / متابعة" value={d.classification_note} onChange={v=>set(s=>({...s,classification_note:v}))}/><TextArea label="سبب التعديل" value={d.reason} onChange={v=>set(s=>({...s,reason:v}))} required/><ErrorNotice error={c.error}/><SaveBar pending={c.pending} label="حفظ المتابعة"/></form>;}
function FeeForm({id,onDone}:{id:number;onDone:(id:number)=>void}){const c=useCommand();const o=useOptions();const [amount,setAmount]=useState('');const [date,setDate]=useState(today());const [tax,setTax]=useState('');const [reason,setReason]=useState('');return <form className="ops-form" onSubmit={async e=>{e.preventDefault();const r=await c.run<ApiEnvelope<{expense_id:number}>>(`checks/${id}/fees`,{amount,document_date:date,tax_code_id:Number(tax),reason});if(r)onDone(r.data.expense_id);}}><Field label="تاريخ الرسوم" type="date" value={date} onChange={e=>setDate(e.target.value)} required/><Field label="قيمة الرسوم بعملة الشيك" value={amount} onChange={e=>setAmount(e.target.value)} required inputMode="decimal"/><Select label="المعاملة الضريبية حسب مستند البنك" value={tax} onChange={setTax} options={optionRows(o.data?.data.taxes)}/><TextArea label="المرجع والسبب" value={reason} onChange={setReason} required/><p className="muted">ينشئ سند مصروف من الحساب البنكي المرتبط بالإيداع؛ راجعه واعتمده ثم رحّله لإثبات الرسوم.</p><ErrorNotice error={c.error}/><SaveBar pending={c.pending} label="إنشاء سند الرسوم"/></form>;}
