import { useState } from 'react';
import { DeleteDraftButton } from '../../components/ui/DeleteAction';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { ErrorNotice, Field, Loading, Modal } from '../../components/ui/Primitives';
import type { ApiEnvelope } from '../../lib/api/client';
import { useAuth } from '../../lib/auth/context';
import { DocumentSummary, Heading, ListTable, PaymentFields, PostButton, PrintButton, SaveBar, Select, StateBadge, TextArea, money, optionRows, today, useChoices, useCommand, useOptions, useRecord, type BasicDocument } from './shared';
type Settlement=BasicDocument&{kind:string;sales_invoice_id:number;target_invoice_id?:number;customer_id:number;payment_id?:number;payload:{balance:{remaining:string};account_id?:number}};
const labels:Record<string,string>={refund:'رد رصيد دائن للعميل',apply_credit:'استخدام رصيد في فاتورة أخرى',early_settlement:'تسوية مبكرة بخصم تحصيل'};
type Invoice=BasicDocument&{customer_id:number;sale_mode:string};
export function CustomerSettlementsPage(){const {id}=useParams();const [params]=useSearchParams();const [add,setAdd]=useState(params.has('invoice'));const {can}=useAuth();const nav=useNavigate();if(id)return <SettlementDetail key={id} id={Number(id)}/>;return <><Heading title="أرصدة العملاء والتسويات">{(can('sales.cancel')||can('installments.early_settlement'))&&<button className="button" onClick={()=>setAdd(true)}>تسوية جديدة</button>}</Heading><ListTable<Settlement> endpoint="customer-settlements" columns={[{key:'n',label:'المستند',render:r=><Link to={`/sales/settlements/${r.id}`}>{r.document_no??`طلب #${r.id}`}</Link>},{key:'k',label:'نوع التسوية',render:r=>labels[r.kind]},{key:'d',label:'التاريخ',render:r=>r.document_date},{key:'a',label:'المبلغ / الخصم',render:r=><bdi>{money(r.amount)} {r.currency}</bdi>},{key:'s',label:'الحالة',render:r=><StateBadge value={r.status}/>} ]}/>{add&&<Modal title="إنشاء تسوية للعميل" onClose={()=>setAdd(false)}><SettlementForm initialInvoice={params.get('invoice')??''} initialKind={params.get('kind')??'refund'} onSaved={n=>nav(`/sales/settlements/${n}`)}/></Modal>}</>;}
function SettlementForm({initialInvoice,initialKind,onSaved}:{initialInvoice:string;initialKind:string;onSaved:(id:number)=>void}){const {can}=useAuth();const c=useCommand();const o=useOptions();const invoices=useChoices<Invoice>('sales-invoices?status=posted');const [d,set]=useState({kind:initialKind,sales_invoice_id:initialInvoice,target_invoice_id:'',document_date:today(),amount:'',reason:'',method:'cash',cashbox_id:'',bank_account_id:'',account_id:''});const change=(k:string,v:string)=>set(s=>({...s,[k]:v}));const source=invoices.data?.find(i=>i.id===Number(d.sales_invoice_id));return <form className="ops-form" onSubmit={async e=>{e.preventDefault();const r=await c.run<ApiEnvelope<Settlement>>('customer-settlements',{...d,sales_invoice_id:Number(d.sales_invoice_id),target_invoice_id:d.target_invoice_id?Number(d.target_invoice_id):null,account_id:d.account_id?Number(d.account_id):null,cashbox_id:d.cashbox_id?Number(d.cashbox_id):null,bank_account_id:d.bank_account_id?Number(d.bank_account_id):null});if(r)onSaved(r.data.id);}}><Select label="نوع التسوية" value={d.kind} onChange={v=>change('kind',v)} options={Object.entries(labels).filter(([k])=>can(k==='early_settlement'?'installments.early_settlement':'sales.cancel')).map(([value,label])=>({value,label}))}/><Select label="الفاتورة صاحبة الرصيد" value={d.sales_invoice_id} onChange={v=>{change('sales_invoice_id',v);change('target_invoice_id','');}} options={(invoices.data??[]).filter(i=>d.kind!=='early_settlement'||i.sale_mode==='installment').map(i=>({value:i.id,label:`${i.document_no} · ${i.customer_snapshot?.name} · ${i.currency}`}))}/><Field label="التاريخ" type="date" value={d.document_date} onChange={e=>change('document_date',e.target.value)} required/><Field label={d.kind==='early_settlement'?'قيمة خصم التحصيل':'المبلغ المراد استخدامه أو رده'} value={d.amount} onChange={e=>change('amount',e.target.value)} inputMode="decimal" required/>{d.kind==='apply_credit'?<Select label="الفاتورة المستفيدة" value={d.target_invoice_id} onChange={v=>change('target_invoice_id',v)} options={(invoices.data??[]).filter(i=>i.id!==source?.id&&i.customer_id===source?.customer_id&&i.currency===source.currency).map(i=>({value:i.id,label:i.document_no??String(i.id)}))}/>:<PaymentFields options={o.data?.data} currency={source?.currency??'ILS'} method={d.method} cashbox={d.cashbox_id} bank={d.bank_account_id} onChange={change}/>} {d.kind==='early_settlement'&&<><Select label="حساب مصروف خصم التحصيل" value={d.account_id} onChange={v=>change('account_id',v)} options={optionRows(o.data?.data.accounts)}/><p className="notice">يُطلب اعتماد الخصم أولاً. عند الترحيل يُثبت الخصم كمصروف تحصيل ويُقبض باقي الرصيد كاملاً ضمن المعاملة نفسها. لا يعدّل هذا الخصم ضريبة الفاتورة الأصلية.</p></>}<TextArea label="سبب التسوية" value={d.reason} onChange={v=>change('reason',v)} required/><ErrorNotice error={c.error??invoices.error??o.error}/><SaveBar pending={c.pending} label="حفظ طلب التسوية"/></form>;}
function SettlementDetail({id}:{id:number}){const q=useRecord<Settlement>(`customer-settlements/${id}`);const {can}=useAuth();if(q.isPending)return <Loading/>;if(q.error)return <ErrorNotice error={q.error}/>;const d=q.data.data;const content=<><DocumentSummary doc={d}/><section className="panel ops-panel"><h3>{labels[d.kind]}</h3><p>{d.reason}</p><p>الرصيد وقت الطلب: <bdi>{money(d.payload.balance.remaining)} {d.currency}</bdi></p><div className="actions"><Link to={`/sales/invoices/${d.sales_invoice_id}`}>الفاتورة الأصلية</Link><Link to={`/customers/${d.customer_id}/statement`}>كشف العميل</Link>{d.target_invoice_id&&<Link to={`/sales/invoices/${d.target_invoice_id}`}>الفاتورة المستفيدة</Link>}{d.payment_id&&<Link to={`/sales/receipts/${d.payment_id}`}>سند قبض التسوية</Link>}</div></section></>;return <><Heading title={labels[d.kind]}>{d.status==='draft'&&can(d.kind==='early_settlement'?'installments.early_settlement':'sales.cancel')&&<PostButton path={`customer-settlements/${id}/post`}/>}{d.status==='draft'&&can('payments.receive')&&<DeleteDraftButton endpoint={`customer-settlements/${id}`} name={`${labels[d.kind]} #${id}`} backTo="/sales/settlements"/>}<PrintButton title={labels[d.kind]} number={d.document_no??`طلب #${id}`}>{content}</PrintButton></Heading>{content}</>;}
