import { QRCodeSVG } from "qrcode.react";
import { useState } from 'react';
import { Link } from 'react-router-dom';
import type { PermissionName } from '../../types/identity';
import type { ApiEnvelope } from '../../lib/api/client';
import { useAuth } from '../../lib/auth/context';
import { ErrorNotice, Field, Loading, Modal } from '../../components/ui/Primitives';
import { Heading, ListTable, SaveBar, Select, StateBadge, TextArea, Tick, useCommand, useRecord } from './shared';
type Policy={key:string;version:number;settings:Record<string,string|number|boolean>};
const names:Record<string,string>={sales:'سياسة البيع والمرتجعات',installments:'سياسة التقسيط والائتمان',treasury:'سياسة الخزينة والمصروفات',checks:'سياسة الشيكات'};
const fields:Record<string,string>={discount_percent:'نسبة الخصم المسموحة دون موافقة',return_window_days:'مدة الإرجاع بالأيام',segregate_requester:'اشتراط اختلاف طالب الموافقة عن معتمدها',minimum_down_payment_percent:'الحد الأدنى للدفعة الأولى %',allow_credit_override:'السماح بطلب استثناء ائتماني',grace_days:'أيام السماح قبل تصنيف التأخر',enforce_sessions:'اشتراط وردية مفتوحة لحركات الصندوق',expense_approval_threshold:'قيمة المصروف التي تتطلب موافقة',variance_approval_threshold:'قيمة فرق الصندوق التي تتطلب موافقة',allow_early_deposit:'السماح بإيداع الشيك قبل استحقاقه'};
export function OperationsPoliciesPage(){const q=useRecord<Policy[]>('operations/policies');const [editing,setEditing]=useState<Policy>();return <><Heading title="السياسات التشغيلية"/><p className="muted">كل تعديل ينشئ نسخة سياسة جديدة ويُسجل سببه. قد يتطلب المستند الذي ينتظر موافقة إعادة طلبها إذا تغيرت السياسة.</p><ErrorNotice error={q.error}/><div className="ops-grid two">{q.data?.data.map(p=><section key={p.key} className="panel ops-panel"><h2>{names[p.key]}</h2><p>الإصدار {p.version}</p><dl className="ops-definition">{Object.entries(p.settings).map(([k,v])=><div key={k}><dt>{fields[k]??(k==='markup_recognition'?'الاعتراف بسعر التقسيط':'إثبات الذمة عند استلام الشيك')}</dt><dd>{typeof v==='boolean'?v?'مفعّل':'غير مفعّل':v==='unconfigured'?'يتطلب إعداداً':v==='full_price_at_sale'?'السعر الكامل عند البيع':v==='on_receipt'?'عند الاستلام':String(v)}</dd></div>)}</dl><button className="button secondary" onClick={()=>setEditing(p)}>تعديل السياسة</button></section>)}</div>{editing&&<Modal title={names[editing.key]} onClose={()=>setEditing(undefined)}><PolicyForm policy={editing} onSaved={()=>setEditing(undefined)}/></Modal>}</>;}
function PolicyForm({policy,onSaved}:{policy:Policy;onSaved:()=>void}){const c=useCommand();const [settings,set]=useState(policy.settings);const [reason,setReason]=useState('');return <form className="ops-form" onSubmit={async e=>{e.preventDefault();if(await c.run(`operations/policies/${policy.key}`,{version:policy.version,settings,reason},'PUT'))onSaved();}}>{Object.entries(settings).map(([k,v])=>typeof v==='boolean'?<Tick key={k} label={fields[k]??k} value={v} onChange={value=>set(s=>({...s,[k]:value}))}/>:k==='markup_recognition'?<Select key={k} label="الاعتراف بسعر التقسيط" value={String(v)} onChange={value=>set(s=>({...s,[k]:value}))} options={[{value:'unconfigured',label:'غير محدد — يمنع ترحيل التقسيط'},{value:'full_price_at_sale',label:'الاعتراف بالسعر الكامل عند البيع'}]}/>:k==='ar_recognition'?<p key={k}>إثبات سداد الذمة عند استلام الشيك، وإعادتها عند ارتجاعه.</p>:<Field key={k} label={fields[k]??k} value={String(v)} inputMode="decimal" onChange={e=>set(s=>({...s,[k]:typeof v==='number'?Number(e.target.value):e.target.value}))} required/>)}<TextArea label="سبب التعديل" value={reason} onChange={setReason} required/><ErrorNotice error={c.error}/><SaveBar pending={c.pending} label="حفظ إصدار السياسة"/></form>;}
type Approval={id:number;source_type:string;source_id:number;policy_key:string;status:string;reason:string;requested_by:number;decision_reason?:string;created_at:string;payload:string|Record<string,unknown>};
const sources:Record<string,string>={sales_invoice:'استثناء سعر بيع',sales_credit:'استثناء ائتمان',sales_return:'مرتجع خارج المدة',installment_reschedule:'إعادة جدولة',expense:'مصروف',cash_transfer:'حركة خزينة',cash_session_close:'فرق صندوق',check_return:'إعادة شيك للعميل',customer_credit:'خصم تسوية',customer_refund:'رد رصيد عميل'};
export function WorkflowApprovalsPage(){const [selected,setSelected]=useState<Approval>();const {can}=useAuth();const permission:Record<string,PermissionName>={sales:'sales.override_price',installments:'installments.approve',treasury:'expenses.approve',checks:'checks.return_to_customer'};return <><Heading title="موافقات العمليات"/><ListTable<Approval> endpoint="operations/approvals" columns={[{key:'id',label:'الطلب',render:r=>`#${r.id}`},{key:'s',label:'العملية',render:r=>`${sources[r.source_type]??r.source_type} #${r.source_id}`},{key:'p',label:'السياسة',render:r=>names[r.policy_key]},{key:'r',label:'سبب الطلب',render:r=>r.reason},{key:'status',label:'الحالة',render:r=><StateBadge value={r.status}/>},{key:'action',label:'التفاصيل',render:r=><button className="button secondary" onClick={()=>setSelected(r)}>عرض الطلب</button>} ]}/>{selected&&<Modal title={`موافقة #${selected.id}`} onClose={()=>setSelected(undefined)}><ApprovalDetail approval={selected} canDecide={can(permission[selected.policy_key]??'approvals.decide')} onSaved={()=>setSelected(undefined)}/></Modal>}</>;}
function ApprovalDetail({approval,canDecide,onSaved}:{approval:Approval;canDecide:boolean;onSaved:()=>void}){const c=useCommand();const [reason,setReason]=useState('');const [decision,setDecision]=useState('approved');let payload:unknown=approval.payload;try{if(typeof payload==='string')payload=JSON.parse(payload);}catch{/* Preserve a legacy snapshot. */}return <form className="ops-form" onSubmit={async e=>{e.preventDefault();if(await c.run(`operations/approvals/${approval.id}/decide`,{decision,reason}))onSaved();}}><p>{approval.reason}</p><p>طالب الموافقة: #{approval.requested_by} · {approval.created_at}</p><details><summary>لقطة تفاصيل المستند وقت الطلب</summary><pre className="ops-json" dir="ltr">{JSON.stringify(payload,null,2)}</pre></details>{approval.status==='pending'&&canDecide?<><Select label="القرار" value={decision} onChange={setDecision} options={[{value:'approved',label:'اعتماد'},{value:'rejected',label:'رفض'}]}/><TextArea label="سبب القرار" value={reason} onChange={setReason} required/><ErrorNotice error={c.error}/><SaveBar pending={c.pending} label="تثبيت القرار"/></>:<><StateBadge value={approval.status}/><p>{approval.decision_reason}</p></>}</form>;}
export function AccountSecurityPage(){const q=useRecord<{enabled:boolean;recovery_codes_remaining:number}>('auth/mfa');const c=useCommand();const [password,setPassword]=useState('');const [code,setCode]=useState('');const [setup,setSetup]=useState<{secret:string;uri:string}>();const [codes,setCodes]=useState<string[]>([]);if(q.isPending)return <Loading/>;return <><Heading title="أمان حسابي"/><section className="panel ops-panel"><h2>المصادقة الثنائية</h2><p>{q.data?.data.enabled?`مفعّلة · رموز الاسترداد المتبقية: ${q.data.data.recovery_codes_remaining}`:'أضف رمزاً متغيراً من تطبيق المصادقة عند تسجيل الدخول.'}</p><form className="ops-form" onSubmit={async e=>{e.preventDefault();if(q.data?.data.enabled){if(await c.run('auth/mfa/disable',{password,code})){setCode('');setPassword('');setSetup(undefined);}}else if(setup){const r=await c.run<ApiEnvelope<{recovery_codes:string[]}>>('auth/mfa/enable',{code});if(r){setCodes(r.data.recovery_codes);setSetup(undefined);setPassword('');setCode('');}}else{const r=await c.run<ApiEnvelope<{secret:string;uri:string}>>('auth/mfa/setup',{password});if(r)setSetup(r.data);}}}>{!setup&&<Field label="كلمة المرور الحالية" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/>}{setup&&<div className="notice"><p>امسح الرمز بتطبيق المصادقة، أو أدخل المفتاح يدوياً.</p><div className="mfa-qr"><QRCodeSVG value={setup.uri} size={180} marginSize={2}/></div><code dir="ltr" className="mfa-secret">{setup.secret}</code><p>ثم أدخل الرمز الظاهر في التطبيق.</p></div>}{(setup||q.data?.data.enabled)&&<Field label="رمز المصادقة / الاسترداد" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)} required/>}<ErrorNotice error={q.error??c.error}/><SaveBar pending={c.pending} label={q.data?.data.enabled?'إيقاف المصادقة الثنائية':setup?'تأكيد التفعيل':'بدء الإعداد'}/></form>{codes.length>0&&<section className="notice"><h3>احفظ رموز الاسترداد الآن</h3><p>يُستخدم كل رمز مرة واحدة، ولن تُعرض هذه الرموز مجدداً.</p><pre dir="ltr">{codes.join('\n')}</pre><button className="button secondary" onClick={()=>setCodes([])}>حفظتها في مكان آمن</button></section>}</section></>;}
type Notification={id:number;title:string;message:string;path?:string;action_path?:string;read_at?:string;created_at:string};
export function NotificationsPage(){const c=useCommand();return <><Heading title="التنبيهات والمتابعة"/><ErrorNotice error={c.error}/><ListTable<Notification> endpoint="notifications" columns={[{key:'t',label:'التنبيه',render:r=><><strong>{r.title}</strong><p>{r.message}</p></>},{key:'d',label:'التاريخ',render:r=>r.created_at},{key:'a',label:'الإجراء',render:r=><div className="actions">{(r.path??r.action_path)&&<Link to={(r.path??r.action_path)!}>فتح التفاصيل</Link>}{!r.read_at&&<button className="button secondary" disabled={c.pending} onClick={()=>void c.run(`notifications/${r.id}/read`)}>تمت القراءة</button>}</div>} ]}/></>;}
