import { SearchableSelect } from '../../components/ui/SearchableSelect';
import { useRef, useState, type ReactNode } from 'react';
import { keepPreviousData, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import Decimal from 'decimal.js';
import { api, allPages, type ApiEnvelope, type Page } from '../../lib/api/client';
import { DataTable, Filters, Pagination, type Column } from '../../components/data-table/DataTable';
import { Badge, ErrorNotice, Loading, Modal } from '../../components/ui/Primitives';
import { PrintDialog } from '../../components/print/PrintDialog';
import { PrintView } from '../../components/print/PrintView';
export const today = () => new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const money = (v: string | number | null | undefined) => { try { return new Decimal(v ?? 0).toFixed(4).replace(/\.0+$/, ''); } catch { return '—'; } };
export const statusLabels: Record<string,string> = {draft:'مسودة',pending:'بانتظار الموافقة',approved:'معتمد',rejected:'مرفوض',posted:'مرحّل',active:'نشط',completed:'مكتمل',received:'في الحيازة',deposited:'مودع',under_collection:'تحت التحصيل',cleared:'محصّل',bounced:'مرتجع',replaced:'مستبدل',returned:'معاد للعميل',settled:'مسوّى',open:'مفتوحة',closed:'مغلقة',overdue:'متأخر',due:'مستحق',partial:'مدفوع جزئياً',paid:'مسدد',upcoming:'قادم',superseded:'جدول سابق',queued:'قيد الانتظار',processing:'جارٍ التجهيز',failed:'تعذر التجهيز',expired:'انتهت الصلاحية',cash:'نقدي',bank:'بنكي',check:'شيك',credit:'آجل',installment:'تقسيط',applied:'مطبّق'};
export function StateBadge({value}:{value:string}) { return <Badge tone={['posted','completed','paid','cleared','approved'].includes(value)?'good':['bounced','overdue','rejected','failed'].includes(value)?'danger':'neutral'}>{statusLabels[value]??value}</Badge>; }
export type Option = {id:number; name?:string; name_ar?:string; legal_name?:string; trade_name?:string; code?:string; currency_code?:string; purpose?:string; sellable?:boolean; active?:boolean; serial_tracked?:boolean; tax_code_id?:number; effective_from?:string; effective_to?:string|null; rate?:string};
export type Options = {currencies:{code:string;name:string}[]; cashboxes:Option[];banks:Option[];locations:Option[];taxes:Option[];accounts:Option[]};
export function useOptions() { return useQuery({queryKey:['operations-options'],queryFn:()=>api<ApiEnvelope<Options>>('operations/options')}); }
export function useChoices<T>(endpoint:string,enabled=true) { return useQuery({queryKey:['choices',endpoint],queryFn:({signal})=>allPages<T>(endpoint,signal),enabled}); }
export function useRecord<T>(endpoint:string) { return useQuery({queryKey:['document',endpoint],queryFn:()=>api<ApiEnvelope<T>>(endpoint)}); }
export function useCommand() {
  const [pending,setPending]=useState(false);const [error,setError]=useState<unknown>();const client=useQueryClient();const keys=useRef(new Map<string,string>());
  const run=async<T,>(path:string,body:unknown={},method='POST'):Promise<T|undefined>=>{if(pending)return;setPending(true);setError(undefined);const signature=path+JSON.stringify(body);let key=keys.current.get(signature);if(!key){key=crypto.randomUUID();keys.current.set(signature,key);}try{const result=await api<T>(path,{method,body,key});await client.invalidateQueries();return result;}catch(e){setError(e);return undefined;}finally{setPending(false);}};
  return {run,pending,error,setError};
}
export function Heading({title,section,children}:{title:string;section?:string;children?:ReactNode}) { return <header className="page-heading"><div><p className="eyebrow">{section??'العمليات اليومية'}</p><h1>{title}</h1></div><div className="actions">{children}</div></header>; }
export function Select({label,value,onChange,options,required=true,empty='اختر…',disabled=false}:{label:string;value:string|number;onChange:(v:string)=>void;options:{value:string|number;label:string}[];required?:boolean;empty?:string;disabled?:boolean}) { return <label className="field"><span>{label}</span><SearchableSelect value={value} onChange={e=>onChange(e.target.value)} required={required} disabled={disabled}><option value="">{empty}</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</SearchableSelect></label>; }
export const optionRows=(rows:Option[]|undefined)=> (rows??[]).map(o=>({value:o.id,label:([o.code,o.name??o.name_ar??o.legal_name??o.trade_name].filter(Boolean).join(' · '))}));
export function TextArea({label,value,onChange,required=false}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean}) { return <label className="field"><span>{label}</span><textarea rows={3} value={value} onChange={e=>onChange(e.target.value)} required={required}/></label>; }
export function Tick({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}) { return <label className="ops-check"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>; }
export function SaveBar({pending,label='حفظ المسودة',onCancel}:{pending:boolean;label?:string;onCancel?:()=>void}) { return <div className="dialog-actions"><button className="button" disabled={pending}>{pending?'جارٍ الحفظ…':label}</button>{onCancel&&<button className="button secondary" type="button" onClick={onCancel}>إلغاء</button>}</div>; }
// searchable: a debounced text box sent as search=; screens with their own search box pass false.
export function ListTable<T extends {id:number|string}>({endpoint,columns,query='',onRows,searchable=true,searchPlaceholder,filters}:{endpoint:string;columns:Column<T>[];query?:string;onRows?:(rows:T[])=>ReactNode;searchable?:boolean;searchPlaceholder?:string;filters?:ReactNode}) { const [search,setSearch]=useState('');const fullQuery=[query,search?`search=${encodeURIComponent(search)}`:''].filter(Boolean).join('&');const listKey=endpoint+'|'+fullQuery;const [paging,setPaging]=useState({listKey,page:1});const page=paging.listKey===listKey?paging.page:1;const setPage=(p:number)=>setPaging({listKey,page:p});const q=useQuery({queryKey:['operation-list',endpoint,fullQuery,page],queryFn:()=>api<Page<T>>(`${endpoint}${endpoint.includes('?')?'&':'?'}page=${page}${fullQuery?'&'+fullQuery:''}`),placeholderData:keepPreviousData});const box=searchable?<Filters value={search} onChange={setSearch} placeholder={searchPlaceholder}>{filters}</Filters>:filters?<div className="filters">{filters}</div>:null;if(q.isPending||q.error)return <section className="panel">{box}{q.error?<ErrorNotice error={q.error}/>:<Loading/>}</section>;const p=q.data;const last=p.meta?.last_page??p.last_page??1;if(page>last&&last>=1){setPage(last);return <Loading/>;}return <section className="panel">{box}{onRows?.(p.data)}<DataTable rows={p.data} columns={columns}/><Pagination page={p.meta?.current_page??p.current_page??page} last={last} total={p.meta?.total??p.total??p.data.length} onPage={setPage}/></section>; }
export type BasicDocument = {id:number;document_no:string|null;document_date:string;status:string;currency:string;amount?:string;foreign_total?:string;base_amount?:string;base_total?:string;notes?:string|null;reason?:string;description?:string;approval_id?:number|null;posted_journal_entry_id?:number|null;customer_snapshot?:{name:string;phone?:string;address?:string};supplier_snapshot?:{legal_name:string;trade_name?:string};};
export function DocumentSummary({doc}:{doc:BasicDocument}) { return <section className="ops-summary"><div><small>المستند</small><strong>{doc.document_no??`مسودة #${doc.id}`}</strong></div><div><small>التاريخ</small><strong>{doc.document_date}</strong></div><div><small>الطرف</small><strong>{doc.customer_snapshot?.name??doc.supplier_snapshot?.legal_name??'—'}</strong></div><div><small>الإجمالي</small><strong><bdi>{money(doc.amount??doc.foreign_total)} {doc.currency}</bdi></strong></div><div><small>الحالة</small><StateBadge value={doc.status}/></div>{doc.approval_id&&<Link to="/admin/workflow-approvals">طلب الموافقة #{doc.approval_id}</Link>}</section>; }
export function PostButton({path,onSuccess,disabled=false,label='ترحيل المستند'}:{path:string;onSuccess?:()=>void;disabled?:boolean;label?:string}) { const [confirm,setConfirm]=useState(false);const c=useCommand();return <><button className="button" disabled={disabled||c.pending} onClick={()=>setConfirm(true)}>{label}</button>{confirm&&<Modal title={label} onClose={()=>setConfirm(false)}><form className="ops-form" onSubmit={async e=>{e.preventDefault();if(await c.run(path)){setConfirm(false);onSuccess?.();}}}><p>راجع تفاصيل المستند. سيُسجَّل أثره في الحسابات والحركات المرتبطة به.</p><ErrorNotice error={c.error}/><SaveBar pending={c.pending} label="تأكيد الترحيل" onCancel={()=>setConfirm(false)}/></form></Modal>}</>; }
export function ReasonAction({label,path,withDate=false,onSuccess}:{label:string;path:string;withDate?:boolean;onSuccess?:()=>void}) {const [open,setOpen]=useState(false);const [reason,setReason]=useState('');const [date,setDate]=useState(today());const c=useCommand();return <><button className="button secondary" onClick={()=>setOpen(true)}>{label}</button>{open&&<Modal title={label} onClose={()=>setOpen(false)}><form className="ops-form" onSubmit={async e=>{e.preventDefault();if(await c.run(path,{reason,...(withDate?{document_date:date}:{})})){setOpen(false);onSuccess?.();}}}>{withDate&&<label className="field"><span>تاريخ الحركة</span><input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label>}<TextArea label="السبب / الملاحظة" value={reason} onChange={setReason} required/><ErrorNotice error={c.error}/><SaveBar pending={c.pending} label={label}/></form></Modal>}</>;}
export function PrintButton({title,number,children,hideTaxNumber=false}:{title:string;number:string;children:ReactNode;hideTaxNumber?:boolean}) { const [open,setOpen]=useState(false);const store=useRecord<{trade_name?:string;legal_name?:string;address?:string;phone?:string;tax_number?:string}>('store/context');return <><button className="button secondary" onClick={()=>setOpen(true)}>طباعة</button>{open&&<PrintDialog onClose={()=>setOpen(false)}><PrintView title={title} number={number}><div className="ops-print-identity"><h2>{store.data?.data.trade_name}</h2><p>{store.data?.data.legal_name} · {store.data?.data.address} · {store.data?.data.phone}</p>{!hideTaxNumber&&store.data?.data.tax_number&&<p>الرقم الضريبي: {store.data.data.tax_number}</p>}</div>{children}</PrintView></PrintDialog>}</>;}
export function Attachments({type,id,write=false}:{type:string;id:number;write?:boolean}) {const q=useRecord<{id:number;original_name:string;size:number}[]>(`documents/${type}/${id}`);const c=useCommand();return <section className="panel ops-panel"><h3>المرفقات</h3><ErrorNotice error={q.error??c.error}/>{q.data?.data.map(a=><p key={a.id}><a href={`/api/v1/documents/${type}/${id}/${a.id}/download`}>{a.original_name}</a> <small>{Math.ceil(a.size/1024)} KB</small></p>)}{write&&<label className="field"><span>إرفاق PDF أو صورة (حتى 10 MB)</span><input type="file" accept="application/pdf,image/jpeg,image/png" disabled={c.pending} onChange={async e=>{const input=e.currentTarget;const file=input.files?.[0];if(!file)return;const body=new FormData();body.append('file',file);await c.run(`documents/${type}/${id}`,body);input.value='';}}/></label>}</section>; }
export function PaymentFields({options,currency,method,cashbox,bank,onChange,required=true}:{required?:boolean;options:Options|undefined;currency:string;method:string;cashbox:string;bank:string;onChange:(field:string,value:string)=>void}) {return <><Select label="وسيلة الدفع" value={method} onChange={v=>onChange('method',v)} options={[{value:'cash',label:'نقدي'},{value:'bank',label:'تحويل بنكي'}]}/>{method==='cash'?<Select required={required} label="الصندوق" value={cashbox} onChange={v=>onChange('cashbox_id',v)} options={optionRows(options?.cashboxes.filter(o=>o.currency_code===currency))}/>:<Select required={required} label="الحساب البنكي" value={bank} onChange={v=>onChange('bank_account_id',v)} options={optionRows(options?.banks.filter(o=>o.currency_code===currency))}/>}</>;}
