import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import type { ApiEnvelope } from '../../lib/api/client';
import { useAuth } from '../../lib/auth/context';
import { ErrorNotice, Field, Loading, Modal } from '../../components/ui/Primitives';
import { DataTable } from '../../components/data-table/DataTable';
import { Attachments, Heading, ListTable, PrintButton, SaveBar, Select, TextArea, today, useCommand, useRecord } from './shared';
const labels:Record<string,string>={opened:'مفتوح',inspected:'تم الفحص',sent_to_service:'لدى المورد / الصيانة',repaired:'تم الإصلاح',replaced:'تم الاستبدال',rejected:'مرفوض',returned_to_customer:'سُلّم للعميل',closed:'مغلق'};
const transitions:Record<string,string[]>={opened:['inspected'],inspected:['sent_to_service','repaired','replaced','rejected'],sent_to_service:['repaired','replaced','rejected'],repaired:['returned_to_customer'],replaced:['returned_to_customer'],rejected:['returned_to_customer'],returned_to_customer:['closed']};
type Claim={id:number;document_no:string;document_date:string;serial_no:string;customer_id:number;customer_name:string;status:string;covered:boolean;complaint:string;service_reference?:string;events:{id:number;to_status:string;document_date:string;reason:string;service_reference?:string}[]};
export function WarrantyPage(){const {id}=useParams();const [add,setAdd]=useState(false);const nav=useNavigate();const {can}=useAuth();if(id)return <ClaimDetail key={id} id={Number(id)}/>;return <><Heading title="الضمان والصيانة">{can('inventory.transfer')&&<button className="button" onClick={()=>setAdd(true)}>استلام طلب ضمان</button>}</Heading><ListTable<Claim> endpoint="warranty-claims" searchPlaceholder="بحث بالرقم التسلسلي أو العميل أو الطلب" columns={[{key:'n',label:'الطلب',render:r=><Link to={`/inventory/warranty/${r.id}`}>{r.document_no}</Link>},{key:'s',label:'الجهاز',render:r=><bdi>{r.serial_no}</bdi>},{key:'c',label:'العميل',render:r=>r.customer_name},{key:'d',label:'التاريخ',render:r=>r.document_date},{key:'status',label:'الحالة',render:r=>labels[r.status]}]}/>{add&&<Modal title="طلب ضمان جديد" onClose={()=>setAdd(false)}><ClaimForm onSaved={n=>nav(`/inventory/warranty/${n}`)}/></Modal>}</>;}
function ClaimForm({claim,onSaved}:{claim?:Claim;onSaved:(id:number)=>void}){const c=useCommand();const [date,setDate]=useState(today());const [reason,setReason]=useState('');const [serial,setSerial]=useState('');const [reference,setReference]=useState('');const [status,setStatus]=useState(claim?transitions[claim.status]?.[0]??'':'');return <form className="ops-form" onSubmit={async e=>{e.preventDefault();const r=await c.run<ApiEnvelope<Claim>>(claim?`warranty-claims/${claim.id}/transition`:'warranty-claims',claim?{status,document_date:date,reason,service_reference:reference||null,replacement_serial_no:status==='replaced'?serial:null}:{serial_no:serial,document_date:date,complaint:reason});if(r)onSaved(r.data.id);}}>{claim?<Select label="الخطوة التالية" value={status} onChange={setStatus} options={(transitions[claim.status]??[]).map(s=>({value:s,label:labels[s]}))}/>:<Field label="الرقم التسلسلي للجهاز المباع" value={serial} onChange={e=>setSerial(e.target.value)} required/>}{status==='replaced'&&<><Field label="الرقم التسلسلي للجهاز البديل" value={serial} onChange={e=>setSerial(e.target.value)} required/><p className="muted">سجّل المرتجع والبيع البديل أولاً، ثم اربط الجهاز المباع لنفس العميل.</p></>}<Field label="التاريخ" type="date" value={date} onChange={e=>setDate(e.target.value)} required/>{claim&&<Field label="مرجع مركز الصيانة / المورد" value={reference} onChange={e=>setReference(e.target.value)}/>}<TextArea label={claim?'نتيجة الإجراء وسببه':'شكوى العميل ووصف الحالة'} value={reason} onChange={setReason} required/><ErrorNotice error={c.error}/><SaveBar pending={c.pending} label={claim?'تسجيل الإجراء':'فتح الطلب'}/></form>;}
function ClaimDetail({id}:{id:number}){const q=useRecord<Claim>(`warranty-claims/${id}`);const [action,setAction]=useState(false);const {can}=useAuth();if(q.isPending)return <Loading/>;if(q.error)return <ErrorNotice error={q.error}/>;const d=q.data.data;const content=<><section className="ops-summary"><div><small>الجهاز</small><strong><bdi>{d.serial_no}</bdi></strong></div><div><small>العميل</small><strong>{d.customer_name}</strong></div><div><small>الحالة</small><strong>{labels[d.status]}</strong></div><div><small>ضمن مدة الضمان عند الطلب</small><strong>{d.covered?'نعم':'لا'}</strong></div></section><p>{d.complaint}</p><p>مرجع الصيانة: {d.service_reference??'—'}</p><DataTable rows={d.events} columns={[{key:'d',label:'التاريخ',render:r=>r.document_date},{key:'s',label:'الإجراء',render:r=>labels[r.to_status]},{key:'r',label:'التفاصيل',render:r=>r.reason},{key:'ref',label:'المرجع',render:r=>r.service_reference}]}/></>;return <><Heading title={d.document_no}>{d.status!=='closed'&&can('inventory.transfer')&&<button className="button" onClick={()=>setAction(true)}>تحديث حالة الطلب</button>}<PrintButton title="طلب ضمان وصيانة" number={d.document_no}>{content}</PrintButton></Heading>{content}<p className="muted">هذا الطلب يتتبع جهاز العميل بعهدة الصيانة، ولا يضيف ملكية الجهاز إلى مخزون المتجر.</p><Attachments type="warranty_claim" id={id} write={can('inventory.transfer')}/>{action&&<Modal title="إجراء على طلب الضمان" onClose={()=>setAction(false)}><ClaimForm claim={d} onSaved={()=>setAction(false)}/></Modal>}</>;}
