import type { GoodsReceipt, ReceiptLine } from "./receiptTypes";
export type InvoicePolicy = {
  version: number;
  price_variance_mode: "block" | "post_to_expense";
  price_variance_account_id: number | null;
  nonrecoverable_tax_mode: "block" | "expense";
  nonrecoverable_tax_account_id: number | null;
  require_attachment: boolean;
};
export type InvoiceLine = {
  id: number;
  goods_receipt_line_id: number;
  goods_receipt_id?: number;
  receipt_document_no?: string;
  product_snapshot: ReceiptLine["product_snapshot"];
  quantity: string;
  unit_price: string;
  discount_amount: string;
  tax_code_id: number;
  tax_snapshot: { name_ar: string; category: string };
  tax_inclusive: boolean;
  tax_recoverable: boolean;
  tax_rate: string;
  taxable_base: string;
  tax_amount: string;
  total: string;
  base_total: string;
  receipt_foreign_value: string;
  receipt_base_value: string;
  price_variance: string;
  fx_variance: string;
};
export type SupplierInvoice = {
  id: number;
  document_no: string | null;
  supplier_id: number;
  supplier_snapshot: GoodsReceipt["supplier_snapshot"];
  supplier_invoice_no: string;
  invoice_date: string;
  posting_date: string;
  due_date: string;
  currency: string;
  base_currency: string;
  exchange_rate: string;
  exchange_rate_date: string;
  exchange_rate_source: string;
  version: number;
  status: string;
  net_total: string;
  tax_total: string;
  foreign_total: string;
  base_total: string;
  grni_total: string;
  price_variance_total: string;
  fx_variance_total: string;
  variance_reason: string | null;
  notes: string | null;
  posted_journal_entry_id: number | null;
  lines: InvoiceLine[];
  policy_snapshot: InvoicePolicy;
};
export type MatchingReceipt = Omit<GoodsReceipt, "lines"> & {
  lines: (ReceiptLine & { uninvoiced_quantity: string })[];
};
