<?php
namespace App\Http\Controllers\Api\V1;
use App\Domains\Checks\Actions\ManageCheck;
use App\Domains\Approvals\Actions\BusinessApproval;
use App\Domains\Payments\Actions\ReceiveCustomerPayment;
use App\Domains\Audit\Actions\RecordAudit;
use App\Http\Controllers\Controller;
use App\Http\Requests\OperationRules;
use App\Support\BusinessException;
use App\Support\Decimal;
use App\Support\IdempotentRequest;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
class CheckController extends Controller {
    public function followup(Request $r,int $id):JsonResponse{
        $d=$r->validate(['due_date'=>['required','date_format:Y-m-d'],'followup_on'=>['nullable','date_format:Y-m-d'],'classification_note'=>['nullable','string','max:1000'],'reason'=>['required','string','min:5','max:1000']]);
        DB::transaction(function()use($id,$d,$r){$c=DB::table('checks')->where('id',$id)->lockForUpdate()->first();abort_unless($c,404);if($d['due_date']!==$c->due_date&&($c->status!=='received'||$d['due_date']<$c->issue_date))throw new BusinessException('CHECK_DUE_DATE_LOCKED','تعديل الاستحقاق متاح قبل الإيداع فقط ولا يسبق التحرير.');$before=['due_date'=>$c->due_date,'followup_on'=>$c->followup_on,'classification_note'=>$c->classification_note];DB::table('checks')->where('id',$id)->update(['due_date'=>$d['due_date'],'followup_on'=>$d['followup_on']??null,'followup_by'=>$r->user()->id,'classification_note'=>$d['classification_note']??null,'updated_at'=>now()]);DB::table('check_status_history')->insert(['check_id'=>$id,'from_status'=>$c->status,'to_status'=>$c->status,'event_date'=>today()->toDateString(),'reason'=>$d['reason'].' · موعد الاستحقاق '.$c->due_date.' ← '.$d['due_date'],'actor_id'=>$r->user()->id,'created_at'=>now()]);app(RecordAudit::class)->execute('checks.followup_updated','check',$id,$before,$d,$r->user()->id);},5);return $this->show($id);
    }
    public function fees(Request $r,int $id,IdempotentRequest $idem):JsonResponse{
        $c=DB::table('checks')->find($id);abort_unless($c,404);if($r->isMethod('get'))return response()->json(['data'=>DB::table('check_fees as f')->join('expenses as e','e.id','=','f.expense_id')->where('f.check_id',$id)->select('f.id','e.id as expense_id','e.document_no','e.amount','e.currency','e.status','e.description')->orderByDesc('f.id')->get()]);
        abort_unless($r->user()->hasPermission('expenses.create'),403);$d=$r->validate(['document_date'=>OperationRules::date(),'amount'=>OperationRules::money(),'tax_code_id'=>['required','integer','exists:tax_codes,id'],'reason'=>['required','string','min:5','max:1000']]);if(!$c->bank_account_id)throw new BusinessException('CHECK_BANK_REQUIRED','اربط الشيك بإيداع بنكي قبل تسجيل رسومه.');
        $result=$idem->execute($r->user()->id,'check.fee.'.$id,(string)$r->header('Idempotency-Key'),$d,function()use($id,$c,$d,$r){return DB::transaction(function()use($id,$c,$d,$r){$expense=app(\App\Domains\Expenses\Actions\ManageExpense::class)->save(['document_date'=>$d['document_date'],'currency'=>$c->currency,'amount'=>$d['amount'],'description'=>'رسوم شيك '.$c->check_no.' — '.$d['reason'],'payee'=>$c->bank_name,'account_id'=>\App\Support\Posting::account('bank_fees','expense'),'method'=>'bank','cashbox_id'=>null,'bank_account_id'=>$c->bank_account_id,'tax_code_id'=>$d['tax_code_id'],'tax_inclusive'=>true,'tax_recoverable'=>false],$r->user()->id);DB::table('check_fees')->insert(['check_id'=>$id,'expense_id'=>$expense->id,'created_by'=>$r->user()->id,'created_at'=>now()]);return ['expense_id'=>$expense->id];},5);});return response()->json(['data'=>$result],201);
    }
    public function index(Request $r):JsonResponse{$d=$r->validate(['status'=>['nullable',Rule::in(['received','deposited','under_collection','cleared','bounced','replaced','returned','settled'])],'due_to'=>['nullable','date_format:Y-m-d'],'search'=>['nullable','string','max:120'],'customer_id'=>['nullable','integer']]);return response()->json(DB::table('checks as c')->join('customers as u','u.id','=','c.customer_id')->when($d['status']??null,fn($q,$v)=>$q->where('c.status',$v))->when($d['due_to']??null,fn($q,$v)=>$q->where('c.due_date','<=',$v))->when($d['search']??null,fn($q,$s)=>$q->where(fn($q)=>$q->where('c.check_no','like',"%$s%")->orWhere('u.name','like',"%$s%")))->when($d['customer_id']??null,fn($q,$v)=>$q->where('customer_id',$v))->select('c.*','u.name as customer_name')->orderBy('due_date')->orderByDesc('c.id')->paginate(\App\Support\PerPage::resolve(25)));}
    public function show(int $id):JsonResponse{$c=DB::table('checks')->find($id);abort_unless($c,404);return response()->json(['data'=>[...(array)$c,'history'=>DB::table('check_status_history')->where('check_id',$id)->orderBy('id')->get(),'allocations'=>DB::table('payment_allocations')->where('customer_payment_id',$c->source_payment_id)->get()]]);}
    public function store(Request $r,IdempotentRequest $idem):JsonResponse{$d=$r->validate(OperationRules::check());$result=$idem->execute($r->user()->id,'check.receive',(string)$r->header('Idempotency-Key'),$d,fn()=>['id'=>app(ManageCheck::class)->receive($d,$r->user()->id)->id]);return $this->show($result['id']);}
    public function transition(Request $r,int $id,IdempotentRequest $idem):JsonResponse{$d=$r->validate(['document_date'=>OperationRules::date(),'reason'=>['required','string','min:5','max:1000']]);$event=$r->route('checkEvent');$result=$idem->execute($r->user()->id,'check.'.$event.'.'.$id,(string)$r->header('Idempotency-Key'),$d,fn()=>['id'=>app(ManageCheck::class)->transition($id,$event,$d,$r->user()->id)->id]);return $this->show($result['id']);}
    public function requestReturn(Request $r,int $id):JsonResponse{
        $d=$r->validate(['reason'=>['required','string','min:5','max:1000']]);DB::transaction(function()use($id,$d,$r){$c=DB::table('checks')->where('id',$id)->lockForUpdate()->first();abort_unless($c,404);if($c->status!=='received')throw new BusinessException('CHECK_NOT_RETURNABLE','الشيك ليس في حيازة المتجر.');$a=app(BusinessApproval::class)->request('check_return',$id,1,'checks',['check_id'=>$id,'source_payment_id'=>$c->source_payment_id,'amount'=>$c->amount,'currency'=>$c->currency],$d['reason'],$r->user()->id);DB::table('checks')->where('id',$id)->update(['return_approval_id'=>$a]);});return $this->show($id);
    }
    public function replace(Request $r,int $id,IdempotentRequest $idem):JsonResponse{$d=$r->validate(OperationRules::check());$d['customer_id']=(int)$d['customer_id'];$result=$idem->execute($r->user()->id,'check.replace.'.$id,(string)$r->header('Idempotency-Key'),$d,fn()=>['id'=>app(ManageCheck::class)->replace($id,$d,$r->user()->id)->id]);return $this->show($result['id']);}
    public function settle(Request $r,int $id,IdempotentRequest $idem):JsonResponse{
        $d=$r->validate(OperationRules::payment());$result=$idem->execute($r->user()->id,'check.settle.'.$id,(string)$r->header('Idempotency-Key'),$d,function()use($d,$id,$r){return DB::transaction(function()use($d,$id,$r){$c=DB::table('checks')->where('id',$id)->lockForUpdate()->first();abort_unless($c,404);if($c->status!=='bounced'||$c->customer_id!==(int)$d['customer_id']||$c->currency!==$d['currency']||Decimal::cmp($c->amount,$d['amount'])!==0||$d['document_date']<$c->last_event_date)throw new BusinessException('CHECK_SETTLEMENT_INVALID','التسوية تتطلب نفس العميل والمبلغ والعملة وتاريخاً لا يسبق الارتجاع.');$d['allocations']=DB::table('payment_allocations')->where('customer_payment_id',$c->source_payment_id)->get(['sales_invoice_id','amount'])->map(fn($a)=>(array)$a)->all();$payment=app(ReceiveCustomerPayment::class)->save($d,$r->user()->id);app(ReceiveCustomerPayment::class)->post($payment->id,$r->user()->id);DB::table('checks')->where('id',$id)->update(['status'=>'settled','settlement_payment_id'=>$payment->id,'last_event_date'=>$d['document_date'],'updated_at'=>now()]);DB::table('check_status_history')->insert(['check_id'=>$id,'from_status'=>'bounced','to_status'=>'settled','event_date'=>$d['document_date'],'reason'=>'تسوية بسند قبض','actor_id'=>$r->user()->id,'created_at'=>now()]);app(RecordAudit::class)->execute('checks.settled','check',$id,null,['payment_id'=>$payment->id],$r->user()->id);return ['id'=>$id];},5);});return $this->show($result['id']);
    }
    public function settlementPayments(int $id):JsonResponse{$c=DB::table('checks')->find($id);abort_unless($c,404);return response()->json(['data'=>$c->status==='bounced'?app(ManageCheck::class)->settlementCandidates($c):[]]);}
    public function settleExisting(Request $r,int $id,IdempotentRequest $idem):JsonResponse{
        $d=$r->validate(['customer_payment_id'=>['required','integer','exists:customer_payments,id'],'document_date'=>OperationRules::date(),'reason'=>['required','string','min:5','max:1000']]);
        $result=$idem->execute($r->user()->id,'check.settle-existing.'.$id,(string)$r->header('Idempotency-Key'),$d,fn()=>['id'=>app(ManageCheck::class)->settleWithPayment($id,(int)$d['customer_payment_id'],$d['document_date'],$d['reason'],$r->user()->id)->id]);
        return $this->show($result['id']);
    }
    public function batches(Request $r,IdempotentRequest $idem):JsonResponse{
        if($r->isMethod('get'))return response()->json(DB::table('check_deposit_batches')->tap(fn($q)=>\App\Support\Search::apply($q,$r->query('search'),['document_no']))->orderByDesc('id')->paginate(\App\Support\PerPage::resolve(25)));$d=$r->validate(['document_date'=>OperationRules::date(),'bank_account_id'=>['required','integer','exists:bank_accounts,id'],'check_ids'=>['required','array','min:1','max:100'],'check_ids.*'=>['integer','distinct','exists:checks,id'],'reason'=>['required','string','min:5','max:1000']]);$result=$idem->execute($r->user()->id,'check.deposit_batch',(string)$r->header('Idempotency-Key'),$d,fn()=>['id'=>app(ManageCheck::class)->deposit($d,$r->user()->id)->id]);return $this->batch($result['id']);
    }
    public function batch(int $id):JsonResponse{$b=DB::table('check_deposit_batches')->find($id);abort_unless($b,404);return response()->json(['data'=>[...(array)$b,'checks'=>DB::table('check_deposit_batch_items as i')->join('checks as c','c.id','=','i.check_id')->where('i.batch_id',$id)->select('c.*')->get()]]);}
}
