<?php
namespace App\Http\Controllers\Api\V1;
use App\Domains\CashBank\Actions\ManageCashSession;
use App\Domains\CashBank\Actions\TransferCash;
use App\Domains\Expenses\Actions\ManageExpense;
use App\Domains\Audit\Actions\RecordAudit;
use App\Http\Controllers\Controller;
use App\Http\Requests\OperationRules;
use App\Support\BusinessException;
use App\Support\Decimal;
use App\Support\IdempotentRequest;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
class TreasuryController extends Controller {
    public function documents(Request $r,IdempotentRequest $idem):JsonResponse{
        $table=$r->route('treasuryKind');if($r->isMethod('get'))return response()->json(DB::table($table)->tap(fn($q)=>\App\Support\Search::apply($q,$r->query('search'),['document_no','description']))->orderByDesc('id')->paginate(\App\Support\PerPage::resolve(25)));
        $rules=['document_date'=>OperationRules::date(),'currency'=>['required','string','size:3'],'amount'=>OperationRules::money(),'description'=>['required','string','min:5','max:1000']];
        $rules+=$table==='expenses'?['payee'=>['required','string','max:200'],'account_id'=>['required','integer','exists:accounts,id'],'method'=>['required',Rule::in(['cash','bank'])],'cashbox_id'=>['nullable','required_if:method,cash','integer','exists:cashboxes,id'],'bank_account_id'=>['nullable','required_if:method,bank','integer','exists:bank_accounts,id'],'tax_code_id'=>['required','integer','exists:tax_codes,id'],'tax_inclusive'=>['required','boolean'],'tax_recoverable'=>['required','boolean']]:['kind'=>['required',Rule::in(['transfer','capital','drawings'])],'from_method'=>['required',Rule::in(['cash','bank'])],'to_method'=>['required',Rule::in(['cash','bank'])],'from_id'=>['nullable','required_unless:kind,capital','integer','min:1'],'to_id'=>['nullable','required_unless:kind,drawings','integer','min:1']];
        $d=$r->validate($rules);$result=$idem->execute($r->user()->id,$table.'.create',(string)$r->header('Idempotency-Key'),$d,fn()=>['id'=>app($table==='expenses'?ManageExpense::class:TransferCash::class)->save($d,$r->user()->id)->id]);return $this->document($r,$result['id']);
    }
    public function document(Request $r,int $id):JsonResponse{$row=DB::table($r->route('treasuryKind'))->find($id);abort_unless($row,404);$row->payload=json_decode($row->payload,true,512,JSON_THROW_ON_ERROR);$row->kind=$row->payload['kind']??null;$row->payee=$row->payload['payee']??null;return response()->json(['data'=>$row]);}
    public function post(Request $r,int $id,IdempotentRequest $idem):JsonResponse{$table=$r->route('treasuryKind');$idem->execute($r->user()->id,$table.'.post.'.$id,(string)$r->header('Idempotency-Key'),[],fn()=>['id'=>app($table==='expenses'?ManageExpense::class:TransferCash::class)->post($id,$r->user()->id)->id]);return $this->document($r,$id);}
    public function sessions(Request $r,IdempotentRequest $idem):JsonResponse{if($r->isMethod('get'))return response()->json(DB::table('cashier_sessions as s')->join('cashboxes as c','c.id','=','s.cashbox_id')->when(!$r->user()->hasPermission('cashbank.manage'),fn($q)=>$q->where('s.cashier_id',$r->user()->id))->tap(fn($q)=>\App\Support\Search::apply($q,$r->query('search'),['s.document_no','c.name']))->orderByDesc('s.id')->select('s.*','c.name as cashbox_name','c.currency_code as currency')->paginate(\App\Support\PerPage::resolve(25)));$d=$r->validate(['cashbox_id'=>['required','integer','exists:cashboxes,id'],'opening_amount'=>OperationRules::money(),'reason'=>['required','string','min:5','max:1000']]);$result=$idem->execute($r->user()->id,'session.open',(string)$r->header('Idempotency-Key'),$d,fn()=>['id'=>app(ManageCashSession::class)->open($d,$r->user()->id)->id]);return $this->session($r,$result['id']);}
    public function session(Request $r,int $id):JsonResponse{$d=app(ManageCashSession::class)->detail($id);abort_unless($d->cashier_id===$r->user()->id||$r->user()->hasPermission('cashbank.manage'),403);return response()->json(['data'=>$d]);}
    public function close(Request $r,int $id):JsonResponse{$this->session($r,$id);$d=$r->validate(['counted_amount'=>OperationRules::money(),'reason'=>['required','string','min:5','max:1000']]);return response()->json(['data'=>app(ManageCashSession::class)->close($id,$d,$r->user()->id)]);}
    public function bank(Request $r):JsonResponse{$d=$r->validate(['bank_account_id'=>['required','integer','exists:bank_accounts,id']]);$statements=DB::table('bank_statement_lines as s')->leftJoin('bank_reconciliations as r','r.statement_line_id','=','s.id')->where('s.bank_account_id',$d['bank_account_id'])->select('s.*','r.treasury_movement_id')->orderByDesc('s.id')->paginate(\App\Support\PerPage::resolve(50));$moves=DB::table('treasury_movements as m')->join('journal_lines as l','l.id','=','m.journal_line_id')->join('journal_entries as e','e.id','=','l.journal_entry_id')->leftJoin('bank_reconciliations as r','r.treasury_movement_id','=','m.id')->where('m.bank_account_id',$d['bank_account_id'])->whereNull('r.id')->select('m.*','e.reference_type as source_type','e.reference_id as source_id')->orderByDesc('m.id')->limit(200)->get();return response()->json([...$statements->toArray(),'unmatched_movements'=>$moves]);}
    public function statementLine(Request $r,IdempotentRequest $idem):JsonResponse{$d=$r->validate(['bank_account_id'=>['required','integer','exists:bank_accounts,id'],'document_date'=>OperationRules::date(),'reference'=>['required','string','max:160'],'description'=>['nullable','string','max:1000'],'amount'=>['required','string','regex:/^-?(0|[1-9][0-9]{0,13})(\.[0-9]{1,4})?$/']]);$result=$idem->execute($r->user()->id,'bank.statement_line',(string)$r->header('Idempotency-Key'),$d,function()use($r,$d){$id=DB::table('bank_statement_lines')->insertGetId([...$d,'fingerprint'=>hash('sha256',json_encode($d,JSON_THROW_ON_ERROR)),'created_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);app(RecordAudit::class)->execute('bank.statement_added','bank_statement_line',$id,null,$d,$r->user()->id);return ['id'=>$id];});return response()->json(['data'=>DB::table('bank_statement_lines')->find($result['id'])]);}
    public function reconcile(Request $r,IdempotentRequest $idem):JsonResponse{$d=$r->validate(['statement_line_id'=>['required','integer','exists:bank_statement_lines,id'],'treasury_movement_id'=>['required','integer','exists:treasury_movements,id'],'reason'=>['required','string','min:5','max:1000']]);$result=$idem->execute($r->user()->id,'bank.reconcile',(string)$r->header('Idempotency-Key'),$d,function()use($r,$d){return DB::transaction(function()use($r,$d){$s=DB::table('bank_statement_lines')->where('id',$d['statement_line_id'])->lockForUpdate()->first();$m=DB::table('treasury_movements')->where('id',$d['treasury_movement_id'])->lockForUpdate()->first();if($s->bank_account_id!==$m->bank_account_id||Decimal::cmp($s->amount,$m->amount)!==0)throw new BusinessException('BANK_MATCH_MISMATCH','المبلغ والحساب البنكي لا يتطابقان.');$id=DB::table('bank_reconciliations')->insertGetId([...$d,'created_by'=>$r->user()->id,'created_at'=>now()]);app(RecordAudit::class)->execute('bank.reconciled','bank_reconciliation',$id,null,$d,$r->user()->id);return ['id'=>$id];},5);});return response()->json(['data'=>DB::table('bank_reconciliations')->find($result['id'])]);}
}
