<?php
namespace App\Http\Controllers\Api\V1;
use App\Domains\Audit\Actions\RecordAudit;
use App\Domains\StoreSetup\Actions\NextDocumentNumber;
use App\Http\Controllers\Controller;
use App\Http\Requests\OperationRules;
use App\Support\BusinessException;
use App\Support\IdempotentRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
class WarrantyController extends Controller {
    public function index(Request $r){$d=$r->validate(['search'=>['nullable','string','max:120'],'status'=>['nullable','string','max:40']]);return response()->json(DB::table('warranty_claims as w')->join('serial_numbers as s','s.id','=','w.serial_id')->join('customers as c','c.id','=','w.customer_id')->when($d['search']??null,fn($q,$v)=>$q->where(fn($q)=>$q->where('w.document_no','like',"%$v%")->orWhere('s.serial_no','like',"%$v%")->orWhere('c.name','like',"%$v%")))->when($d['status']??null,fn($q,$v)=>$q->where('w.status',$v))->select('w.*','s.serial_no','c.name as customer_name')->orderByDesc('w.id')->paginate(\App\Support\PerPage::resolve(25)));}
    public function show(int $id){$w=DB::table('warranty_claims as w')->join('serial_numbers as s','s.id','=','w.serial_id')->join('customers as c','c.id','=','w.customer_id')->where('w.id',$id)->select('w.*','s.serial_no','c.name as customer_name')->first();abort_unless($w,404);$w->warranty_snapshot=$w->warranty_snapshot?json_decode($w->warranty_snapshot,true):null;$w->events=DB::table('warranty_events')->where('claim_id',$id)->orderBy('id')->get();return response()->json(['data'=>$w]);}
    public function store(Request $r,IdempotentRequest $idem){$d=$r->validate(['serial_no'=>['required','string','max:120'],'document_date'=>OperationRules::date(),'complaint'=>['required','string','min:5','max:2000']]);$result=$idem->execute($r->user()->id,'warranty.open',(string)$r->header('Idempotency-Key'),$d,function()use($r,$d){return DB::transaction(function()use($r,$d){
        $serial=DB::table('serial_numbers')->where('serial_no',\App\Domains\Inventory\Actions\StockLedger::normalizeSerial($d['serial_no']))->lockForUpdate()->first();if(!$serial||$serial->status!=='sold'||!$serial->sold_sales_line_id)throw new BusinessException('WARRANTY_SALE_REQUIRED','اختر جهازاً مباعاً ومسجلاً برقم تسلسلي.');
        $line=DB::table('sales_invoice_lines')->find($serial->sold_sales_line_id);$sale=DB::table('sales_invoices')->find($line->sales_invoice_id);if($d['document_date']<$sale->document_date)throw new BusinessException('WARRANTY_DATE_INVALID','التاريخ لا يسبق بيع الجهاز.');
        $id=DB::table('warranty_claims')->insertGetId(['document_no'=>app(NextDocumentNumber::class)->execute('warranty_claim',$d['document_date']),'serial_id'=>$serial->id,'sales_invoice_line_id'=>$line->id,'customer_id'=>$sale->customer_id,'document_date'=>$d['document_date'],'last_event_date'=>$d['document_date'],'complaint'=>$d['complaint'],'covered'=>$serial->warranty_end&&$d['document_date']<=$serial->warranty_end,'warranty_snapshot'=>$line->warranty_snapshot,'created_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);$this->event($id,null,'opened',$d['document_date'],$d['complaint'],null,$r->user()->id);return ['id'=>$id];},5);});return $this->show($result['id']);}
    public function transition(Request $r,int $id,IdempotentRequest $idem){$d=$r->validate(['status'=>['required',Rule::in(['inspected','sent_to_service','repaired','replaced','rejected','returned_to_customer','closed'])],'document_date'=>OperationRules::date(),'reason'=>['required','string','min:5','max:2000'],'service_reference'=>['nullable','string','max:200'],'replacement_serial_no'=>['nullable','required_if:status,replaced','string','max:120']]);$idem->execute($r->user()->id,'warranty.transition.'.$id,(string)$r->header('Idempotency-Key'),$d,function()use($r,$id,$d){return DB::transaction(function()use($r,$id,$d){$w=DB::table('warranty_claims')->where('id',$id)->lockForUpdate()->first();abort_unless($w,404);$allowed=['opened'=>['inspected'],'inspected'=>['sent_to_service','repaired','replaced','rejected'],'sent_to_service'=>['repaired','replaced','rejected'],'repaired'=>['returned_to_customer'],'replaced'=>['returned_to_customer'],'rejected'=>['returned_to_customer'],'returned_to_customer'=>['closed']];if(!in_array($d['status'],$allowed[$w->status]??[])||$d['document_date']<$w->last_event_date)throw new BusinessException('WARRANTY_TRANSITION_INVALID','حالة الطلب أو تاريخه لا يسمحان بهذه الخطوة.');$changes=['status'=>$d['status'],'last_event_date'=>$d['document_date'],'service_reference'=>$d['service_reference']??$w->service_reference,'updated_at'=>now()];
        if($d['status']==='replaced'){$serial=DB::table('serial_numbers')->where('serial_no',\App\Domains\Inventory\Actions\StockLedger::normalizeSerial($d['replacement_serial_no']))->lockForUpdate()->first();if(!$serial||$serial->id===$w->serial_id||$serial->status!=='sold'||$serial->customer_id!==$w->customer_id)throw new BusinessException('WARRANTY_REPLACEMENT_SALE_REQUIRED','سجّل الاستبدال بمرتجع وبيع للجهاز البديل لنفس العميل ثم اربط رقمه التسلسلي.');$changes['replacement_serial_id']=$serial->id;}
        DB::table('warranty_claims')->where('id',$id)->update($changes);$this->event($id,$w->status,$d['status'],$d['document_date'],$d['reason'],$d['service_reference']??null,$r->user()->id);return ['id'=>$id];},5);});return $this->show($id);}
    private function event(int $id,?string $from,string $to,string $date,string $reason,?string $reference,int $actor):void{DB::table('warranty_events')->insert(['claim_id'=>$id,'from_status'=>$from,'to_status'=>$to,'document_date'=>$date,'reason'=>$reason,'service_reference'=>$reference,'actor_id'=>$actor,'created_at'=>now()]);app(RecordAudit::class)->execute('warranty.'.$to,'warranty_claim',$id,null,['from'=>$from,'reason'=>$reason,'service_reference'=>$reference],$actor);}
}
