<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
return new class extends Migration {
    public function up():void {
        if(!Schema::hasTable('customer_settlements'))Schema::create('customer_settlements',function(Blueprint $t){$t->id();$t->string('document_no',80)->nullable()->unique();$t->string('kind',30);$t->string('status',20)->default('draft');$t->foreignId('customer_id')->constrained()->restrictOnDelete();$t->foreignId('sales_invoice_id')->constrained()->restrictOnDelete();$t->foreignId('target_invoice_id')->nullable()->constrained('sales_invoices')->restrictOnDelete();$t->date('document_date');$t->char('currency',3);$t->decimal('amount',18,4);$t->decimal('base_amount',18,4)->default(0);$t->json('payload');$t->string('reason',1000);$t->foreignId('approval_id')->nullable()->constrained('workflow_approvals')->restrictOnDelete();$t->foreignId('payment_id')->nullable()->constrained('customer_payments')->restrictOnDelete();$t->foreignId('posted_journal_entry_id')->nullable()->constrained('journal_entries')->restrictOnDelete();$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->foreignId('posted_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('posted_at')->nullable();$t->timestamps();});
        if(!Schema::hasTable('customer_settlement_allocations'))Schema::create('customer_settlement_allocations',function(Blueprint $t){$t->id();$t->foreignId('settlement_id')->constrained('customer_settlements')->restrictOnDelete();$t->foreignId('sales_invoice_id')->constrained()->restrictOnDelete();$t->decimal('amount',18,4);$t->decimal('base_amount',18,4);$t->date('document_date');$t->timestamp('created_at');$t->unique(['settlement_id','sales_invoice_id'],'customer_settlement_invoice_unique');});
        if(!Schema::hasIndex('customer_settlement_allocations','customer_settlement_invoice_unique'))Schema::table('customer_settlement_allocations',fn(Blueprint $t)=>$t->unique(['settlement_id','sales_invoice_id'],'customer_settlement_invoice_unique'));
        Schema::create('warranty_claims',function(Blueprint $t){$t->id();$t->string('document_no',80)->unique();$t->foreignId('serial_id')->constrained('serial_numbers')->restrictOnDelete();$t->foreignId('sales_invoice_line_id')->constrained()->restrictOnDelete();$t->foreignId('customer_id')->constrained()->restrictOnDelete();$t->date('document_date');$t->date('last_event_date');$t->string('status',40)->default('opened');$t->string('complaint',2000);$t->json('warranty_snapshot')->nullable();$t->boolean('covered');$t->string('service_reference',200)->nullable();$t->foreignId('replacement_serial_id')->nullable()->constrained('serial_numbers')->restrictOnDelete();$t->unsignedBigInteger('open_serial_id')->storedAs("CASE WHEN status = 'closed' THEN NULL ELSE serial_id END")->unique();$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();});
        Schema::create('warranty_events',function(Blueprint $t){$t->id();$t->foreignId('claim_id')->constrained('warranty_claims')->restrictOnDelete();$t->string('from_status',40)->nullable();$t->string('to_status',40);$t->date('document_date');$t->string('reason',2000);$t->string('service_reference',200)->nullable();$t->foreignId('actor_id')->constrained('users')->restrictOnDelete();$t->timestamp('created_at');});
        foreach(['customer_settlement_allocations','warranty_events'] as $table){foreach(['UPDATE','DELETE'] as $event)DB::unprepared("CREATE TRIGGER {$table}_no_".strtolower($event)." BEFORE $event ON $table FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Posted operational history is immutable'");}
        foreach(['UPDATE','DELETE'] as $event)DB::unprepared("CREATE TRIGGER customer_settlements_no_".strtolower($event)." BEFORE $event ON customer_settlements FOR EACH ROW BEGIN IF OLD.status='posted' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Posted settlement is immutable'; END IF; END");
    }
    public function down():void{foreach(['warranty_events','warranty_claims','customer_settlement_allocations','customer_settlements'] as $t)Schema::dropIfExists($t);}
};
